### ISSUE TITLE
Math

### ISSUE THREAD

**Issue by rhiokim** [rhiokim/haroopad#10]

**Comment by kyungw00k** [comment]
MathJax 지원해주세요!
http://www.mathjax.org/

**Comment by rhiokim** [comment]
@kyungw00k 좋소,
이쯤이야 30분 24초 정도면 해결하겠소.

**Comment by rhiokim** [comment]
req: http://haroopad.userecho.com/topic/261577-math-expressions/

**Comment by kyungw00k** [comment]
HarooPad에 미리보기용과 export용 html을 달리 뽑을 수 있어요?

MathJax는 결과가 이미지로 렌더링 되기 때문에 반드시 CDN을 사용해야 할 것 같지만..
그래도 작업할때 미리보기에서는 로컬에 있는 이미지를 가져오게 하는게 속도면에서는 좋을 것 같다는 생각이 드네요.

```
<!DOCTYPE html>
<html>
<head>
<title>MathJax TeX Test Page</title>
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}});
</script>
<script type="text/javascript"
  src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>
</head>
<body>
When $a \ne 0$, there are two solutions to \(ax^2 + bx + c = 0\) and they are
$$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$
</body>
</html>
```

(참고 : http://docs.mathjax.org/en/v1.1-latest/start.html)

제가 함 해볼까염?

**Comment by rhiokim** [comment]
동적으로 처리하는 예제가 여기 있네요. 
- http://cdn.mathjax.org/mathjax/latest/test/sample-dynamic-2.html

example:

``` math
\(
J_\alpha(x) = \sum\limits_{m=0}^\infty \frac{(-1)^m}{m! \, \Gamma(m + \alpha + 1)}{\left({\frac{x}{2}}\right)}^{2 m + \alpha}
\)
```

**Comment by rhiokim** [comment]
http://www.codecogs.com/latex/about.php
