### ISSUE TITLE
custom css styles

### ISSUE THREAD

**Issue by rhiokim** [rhiokim/haroopad#130]
- mac
  
  > ~/Library/Application Support/haroopad/themes
- win
  
  > %program installed directory%themes
- linux

**Comment by phrozen** [comment]
I guess this is where i can change the font...

**Comment by rhiokim** [comment]
@phrozen What do you think about supporting lesscss.org or sass-lang.com?

**Comment by phrozen** [comment]
Actually Sass is my flavor and it would be awesome to support it, although as you already have node backend I would recommend Stylus (http://learnboost.github.io/stylus/) It is not much different actually from either and you benefit from the ease of implementation. What do you think?

Edit: forgot less is implemented in node too. So either of those would be awesome. I use the Sass syntax almost daily (not scss) so I would be inclined for Stylus over Less, but both are good options.

**Comment by rhiokim** [comment]
Stylus looks better than others.
Thank you so much for your comments. Consider your idea :+1:
