### ISSUE TITLE
Can't exit from full screen

### ISSUE THREAD

**Issue by taai** [rhiokim/haroopad#134]
Once you "Enter Full screen", you can't exit from it. There is no clue how to do it. `Esc` doesn't work, `F11` doesn't work.

**Comment by cmpscabral** [comment]
+1

**Comment by rhiokim** [comment]
I'll fix next release. 

`Esc` : getting out of fullscreen mode.
`F11`, `COMMAND( or Ctrl ) + Enter` : toggling fullscreen
