### ISSUE TITLE
Dont run in ubuntu 13.04

### ISSUE THREAD

**Issue by jamlfy** [rhiokim/haroopad#137]
``` console
$ haroopad 
/usr/share/haroopad/haroopad: error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory
```

which is the library?

**Comment by rhiokim** [comment]
~~Please! check here~~

You can get more inforatmion at here.  
http://haroopad.userecho.com/topic/226287-linux-ubuntu-1304-amd64-occur-error-shared-libraries
