### ISSUE TITLE
[Mac]Menu items are out of order

### ISSUE THREAD

**Issue by zer0her0** [rhiokim/haroopad#138]
haroopad on Mac OS X has it's menu items in the wrong order currently.

They are: haroopad, Edit, File, Find, View, Action, Help, Window.

Generally they should be: haroopad, File, Edit, View, Find, Action, Help.

See attached images of haroopad app and Finder(good example of proper order).

![haroopad](https://f.cloud.github.com/assets/18337/927086/67ec3602-ff99-11e2-8590-6896e62c9007.png)
![finder](https://f.cloud.github.com/assets/18337/927087/6852c6e2-ff99-11e2-9b8f-5f3e362fad81.png)

**Comment by rhiokim** [comment]
This is the node-webkit issue. . Haroopad'll absorb when solving it. 
https://github.com/rogerwang/node-webkit/issues/743

**Comment by zer0her0** [comment]
Ah thank you please disregard then. :-)

**Comment by rhiokim** [comment]
It'll be fixed on v0.6.0

**Comment by zer0her0** [comment]
Woohoo. Thanks for the update.
