### ISSUE TITLE
Ubuntu 관련 프로그램에 나오게 해주세요

### ISSUE THREAD

**Issue by r2fresh** [rhiokim/haroopad#143]
md 파일을 오른쪽 버튼 > 다른 프로그램 찾기 클릭

다른 프로그램 표시를 클릭하면, 다른 프로그램은 보이지만 haroopad는 보이지 않네요

등록하면 클릭하면 바로 가기가 가능할듯 합니다.

release에서 고려해 주세요^^

**Comment by rhiokim** [comment]
우분투에서는 mimeapps.list 파일에 관련 프로그램을 직접 등록해주면 됩니다.
해당 파일이 존재하지 않는다면 생성해주시고 아래와 같이 추가해주세요.

```
$ vi ~/.local/share/applications/mimeapps.list

[Added Associations]
text/x-markdown=Haroopad.desktop;
```

향후 버젼에 자동으로 될 수 있도록 할 예정입니다.
