### ISSUE TITLE
tab to space 옵션 필요함.

### ISSUE THREAD

**Issue by zziuni** [rhiokim/haroopad#144]
코드 들여쓰기를 할 때 tab를 쓴느데, 
space, tab 선택 옵션이 있으면 합니다.~

여러줄 코드 붙이기 할때, tab를 쓰고 싶지 않은데 그럴수가 없내요~

**Comment by rhiokim** [comment]
link #153

**Comment by rhiokim** [comment]
0.6.0 버젼에 출시될 예정입니다. 구현 완료되어 해결처리 합니다.
