### ISSUE TITLE
Quit, reopen, temp file is now open

### ISSUE THREAD

**Issue by chmac** [rhiokim/haroopad#152]
On Mac, version 0.4.9.

I open Haroopad (awesome software btw, thanks a lot). I edit a file. I quit (leaving the window open). I start Haroopad again later, the same file is still open (or so I think!). Actually, I'm now editing a file with a random filename `2xj0ddYHsYM.md`, which I assume is an autosave of my previous document.

It's confusing because I think I'm still editing the same file, so I save changes, and then I wonder why they're not in version control. If I was editing a regular file, I'd probably not have noticed, and then later wondered where my changes went...

**Comment by rhiokim** [comment]
Exactly!
The severity of this problem are well aware, as mentioned. This issue will be resolved as soon as possible. 
Thanks @chmac

**Comment by rhiokim** [comment]
When you try to save the restored files, should be specify filename.
It'll be release soon. (v0.6)
