### ISSUE TITLE
Allow multiple instance of Haroopad to open (WIN)

### ISSUE THREAD

**Issue by hoegertn** [rhiokim/haroopad#160]
On Windows it is not possible to open mutliple instance by double-clicking .md files

**Comment by rhiokim** [comment]
It will be fixed in the next version (0.5.1).
Thanks!

**Comment by hoegertn** [comment]
I installed 0.6 and it didn't work

**Comment by rhiokim** [comment]
It'll be fixed again for Window & Linux. (0.7.0)
