### ISSUE TITLE
Generate PDF

### ISSUE THREAD

**Issue by jniggemann** [rhiokim/haroopad#163]
It would be cool if haroopad could create PDF files, perhaps using pandoc...

**Comment by rhiokim** [comment]
Pandoc is cool stuff for Markdown editor. But it has some problems with respect to haroopad.
So we are considering to integrate with pandoc.

Thanks for your idea. :-)

**Comment by jniggemann** [comment]
Cool, thank you!

**Comment by jniggemann** [comment]
Oh, sorry for closing, perhaps you wanted to label this as feature request...

**Comment by Fire-Dragon-DoL** [comment]
I'm a bit "shocked", but using node-webkit, which is by the way a chromium instance, the **print** feature has **save to file** (pdf) directly, much like in chrome. Why do we need to spend time on a pdf generator if it's already inside the software? O.o

**Comment by jniggemann** [comment]
Just tried, it works! Very cool!

**Comment by OvOwl** [comment]
Could someone please give me a hint how to integrate node-webkit? Cause "Export->to File" is grayed out.

**Comment by Fire-Dragon-DoL** [comment]
@OvOwl I have no idea what you mean, haroopad is built on node-webkit

**Comment by OvOwl** [comment]
@Fire-Dragon-DoL Thought so but i try to export a document to pdf and on both, windows and linux "Export>File" is grayed out. How can i achieve that? In linux i could just print the document to pdf, but it is a quit big file then and on windows i need to install an extra pdf printer.

**Comment by Fire-Dragon-DoL** [comment]
@OvOwl it's chromium based, I can just do `File -> Print -> Save to file (pdf)` did you try it?

**Comment by OvOwl** [comment]
@Fire-Dragon-DoL as i said. In linux i know this way but the files are much bigger compared to latex produced pdf files. And in windows it is not working this way (-> extra pdf printer needs to be installed i guess).
so, this is the way to generate pdf files out of haroo?

**Comment by jniggemann** [comment]
@OvOwl Can you please stop spamming this old and closed thread? Unsubscribing...
