### ISSUE TITLE
Generate table of contents TOC

### ISSUE THREAD

**Issue by jniggemann** [rhiokim/haroopad#164]
Feature request: It would be nice if haroopad could create a TOC.
I noticed that there's already a toc.js and tocify.js, but I can't figure out how to use those.

**Comment by rhiokim** [comment]
@jniggemann It is a great idea.
However, Haroopad should be avoid the dynamic TOC generation.
Because the 'Export to PDF', 'Sending Email' and Others. 

We'll find the right way.

**Comment by rhiokim** [comment]
![v0 7 0-001](https://f.cloud.github.com/assets/145777/1044265/9690693a-100e-11e3-9d90-8663dc229c40.gif)

How about this?

**Comment by jniggemann** [comment]
I mostly use markdown to generate PDF documents and I'd like to be able to include the TOC in the PDF output...

**Comment by rhiokim** [comment]
it'll plan to release at v0.10

```
[toc] or [TOC]
```
