### ISSUE TITLE
Favicon (or better application icon)

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [rhiokim/haroopad#168]
Stupid and simple to solve, please add favicon to the application (or whatever is called, the application icon, I don't know). Seems stupid but when you alt+tab and you are writing a software with nodewebkit, seems confusing because everything has the same icon (I'm on debian).

**Comment by rhiokim** [comment]
We have only tested on Ubuntu.
Could you please show me the screenshot & detailed OS information?

**Comment by Fire-Dragon-DoL** [comment]
Yes, I had hard time making a screen while Alt + tab is pressed, so here is only a screen displaying the favicon of the app (top left): 

![haroopad_favicon](https://f.cloud.github.com/assets/1329559/1012173/ef371a0a-0b6a-11e3-9cff-970417ca005b.png)

Notice, I'm using Debian Wheezy, with KDE.

**Comment by rhiokim** [comment]
Thanks you. :-)
It was fixed. release soon!!

**Comment by Fire-Dragon-DoL** [comment]
Thanks to you for this wonderful app =)
