### ISSUE TITLE
Open Recent => Replace current windows instead of opening a new one

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [rhiokim/haroopad#169]
If possible, open recent would be nice if instead of creating a new window, will replace the current one, otherwise I always have to go back to the previous and close it. Same for Open.

**Comment by jniggemann** [comment]
Does node-webkit provide the possibility to open tabs instead of multiple windows?

**Comment by Fire-Dragon-DoL** [comment]
I didn't test it but showing chrome tabs it's not considered good (you won't have access to other tabs). If tabs support is required, it must be built in the app
