### ISSUE TITLE
Live Update 기능

### ISSUE THREAD

**Issue by kyungw00k** [rhiokim/haroopad#171]
Update가 있을때 Live로 받아서 기존 앱을 대체 해주는 기능이 있음 좋을 것 같습니다!
(DMG 받아서 Applications에 넣는게 불편해서 이러는건 아니에요 =_=;)

**Comment by rhiokim** [comment]
버젼업을 좀 줄이면 어떨까요? 1년에 한번 ^_^;;
고민 안했던건 아닌데 크로스 플랫폼을 고려해야 하니 쉽지가 않네요.
- 리눅스나 맥은 그나마... 나은데
- 윈도우만 해도 퍼미션 문제에 레지스트리 꼬일 수 밖에 없고

나중에 웹 버젼으로 만들고 node-webkit 으로 랩핑만 할 수도 있음 ^_^

여러가지 고민중이나 솔플중인 현재로썬 'impossible' :-(

**Comment by kyungw00k** [comment]
여튼 잘 쓰고 있음. 덕분에 블로깅이 늘어가고 있음!
