### ISSUE TITLE
Update is not working [WIN]

### ISSUE THREAD

**Issue by hoegertn** [rhiokim/haroopad#173]
I always have to uninstall Haroopad to install the latest version. This happens on windows.

**Comment by aprilix** [comment]
I think I have the same problem: win7(x64) russian. 
 Information | Description 
-------------|-----------------------------
 Type        | Error
 Date        | Sun Apr 27 2014 18:47:16 GMT+0400 (Московское время (зима))
 File        | file:///C:/Users/4FD5~1/AppData/Local/Temp/nw80980_13257/index.html
 Line Number | 1
 Message     | Uncaught SyntaxError: Unexpected token ﻿

**Comment by rhiokim** [comment]
It was solved.
