### ISSUE TITLE
Where is 0.6.0?

### ISSUE THREAD

**Issue by Southern** [rhiokim/haroopad#176]
The latest version I see in here is 0.3.2, but the haroopad I have is 0.6.0.

**Comment by rhiokim** [comment]
In for the time being, we will develop in private repository.

**Comment by Southern** [comment]
Any way of being added to said repository? Would like to be able to work on bugs I find.

**Comment by jniggemann** [comment]
Why not develop in the public repo?

Colton Baker notifications@github.com schrieb:

> Any way of being added to said repository? Would like to be able to
> work on bugs I find.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rhiokim/haroopad/issues/176#issuecomment-23227127

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Southern** [comment]
Because the public repository doesn't have all of the features that the private development branch has. This repository is stuck on 0.3.2. Why waste time creating a feature that is already created or in the works? The current version of haroopad is 0.6.0. You can see why I would like the updated code, right?

**Comment by rhiokim** [comment]
I fully understood. Thank you for contributing @Southern 

But this project is not only for open source. So for the time being is going to work in a private repository
And we will be open sources at the right time for markdown communities

If there is a problem with using, create tickets.

> And saying in english is defficult for me. Please understand this awkward expression. :-(.

**Comment by anshin** [comment]
I'd like to point out that developing for the older public version also means using the older public version. I can't imagine there's much benefit to keeping an outdated version public, as developers can't fully contribute.
