### ISSUE TITLE
v0.6.0 에서 아래의 인터랙션을 하는경우 에디터가 멈춰버립니다. 

### ISSUE THREAD

**Issue by dsdstudio** [rhiokim/haroopad#178]
안녕하세요.. 

좋은 에디터 만들어주셔서 아주 유용하게 사용하고있습니다. 

사용하던 중 버그를 하나 발견해서 리포팅 합니다 ^^; 

문자를 작성하고 한칸을 띄운뒤 다음 라인으로 내려가서 `Ctrl+delete` 키조합을 누르는경우 node-webkit helper 가 cpu 100%먹으면서 멈춰버리는 현상을 발견했어요.. 

![](http://i3.minus.com/i1t4EnwIvTewP.png)
![](http://i2.minus.com/jgXRotxhobJHU.png)

수정 부탁드립니다 :D

**Comment by rhiokim** [comment]
link - marijnh/CodeMirror#1778
해당 이슈가 수정되면 반영될 예정입니다.  리포팅 감사드립니다. :-)

**Comment by rhiokim** [comment]
최신 버젼(v0.13.0) 으로 확인부탁드려요. 테스트 해보니 발생하지 않는 것 같은데....
발생하면 reopen 해주세요. 감사합니다.
