### ISSUE TITLE
Support multi-language

### ISSUE THREAD

**Issue by rhiokim** [rhiokim/haroopad#191]
- [x] global message
- [x] window menu
- [x] main ui
- [x] preferences window

---

Repository : https://github.com/rhiokim/haroopad-locales <- fork it.
- [x] Korea 
- [x] English - default
- [x] German #189 
- [ ] ~~Japan~~
- [x] Chinese
- [ ] ~~French~~
- [x] Vietnamese
- [x] Russian

**Comment by SamLebarbare** [comment]
I'm here for french translation ;)

**Comment by myrtleTree33** [comment]
I'm here for English and Chinese (:

**Comment by rhiokim** [comment]
We have created a [repository](https://github.com/rhiokim/haroopad-locales) for translation.
If you can help with this project, why don't you join us?

@SamLebarbare, @toiletfreak Thanks. :-)
1. Fork it
2. Translate in your forked repository
3. Commit -m "Added {Country} Translation"
4. Write your name & email in AUTHORS.md
5. Pull request

**Comment by myrtleTree33** [comment]
Hello, Do I fork the develop branch and translate directly (on the English)?

---

*1 Corinthians 10:31 *
So, whether you eat or drink, or whatever you do, do all to the glory of
God.

**Comment by rhiokim** [comment]
@toiletfreak Oops! mistake
Repository is [here](https://github.com/rhiokim/haroopad-locales) and Chinese

**Comment by myrtleTree33** [comment]
오 감사합니다.

**Comment by mattn** [comment]
Hi. It seems japanese translations are finished.
https://github.com/rhiokim/haroopad-locales/tree/master/ja

Do you have plan to release? If it's not finished, I can help you. :)

**Comment by rhiokim** [comment]
@mattn You can update newest language files at now. follow step
1. Execuate Haroopad
2. Wait few second.
3. Open Preference Window.
4. You can see update dialog

**Comment by mattn** [comment]
Hmm, it seems not. it may be a problem of my proxy.

**Comment by mattn** [comment]
Is this latest version? 
![](http://go-gyazo.appspot.com/2b40df70a525b6bc.png)

**Comment by rhiokim** [comment]
You should be set to 'Japanese' in your system locale.

And then you can see it at step 3.
![update-language](https://f.cloud.github.com/assets/145777/2470107/901a1904-b00c-11e3-92e1-0555b233c8a0.png)

**Comment by mattn** [comment]
I'm using windows. What OS do you use?

**Comment by mattn** [comment]
The word `Language Pack` don't seems to be contained in develop branch. How doing check the locale in the code? LANG environment variable?
