### ISSUE TITLE
What's stable version?

### ISSUE THREAD

**Issue by sungjuly** [rhiokim/haroopad#194]
0.3.3, right? ;)

**Comment by jniggemann** [comment]
0.7.0 is... Unfortunately it is developed in a private repository...

Sungju Jin notifications@github.com schrieb:

> 0.3.3, right? ;)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rhiokim/haroopad/issues/194

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
