### ISSUE TITLE
[Mac] 구름입력기에서 한글 입력시 문제

### ISSUE THREAD

**Issue by leehyeonsueng** [rhiokim/haroopad#199]
Mac OSX 10.8.5 에서 [구름 입력기](http://gureum.org)를 사용중에 있습니다.
haroopad는 최신버전인 0.7.0 버전을 사용하고 있구요.

한글 입력시 한단어의 입력이 끝나기전까지 입력된 글자가 보이지 않는 현상이 발생합니다.

예를 들어 한글을 입력하고난뒤 스페이스바를 눌려줘야지만 입력한 한글이라는 글자가 보이는 현상입니다.

**Comment by rhiokim** [comment]
네, 구름 입력기에서 테스트 해봤는데 동일한 문제가 재현되었습니다.

이미 트위터를 통해 피드백 주신 분이 계셨는데 시급하지 않아 검토중입니다.

해결책은 여기를 참고해주세요.
 https://twitter.com/haroopad/status/370494678266703873

!하루패드 사용자중에 구름 입력기를 사용하고 계시는 분들은 이곳을 통해 +1 투표를 해주세요.

**Comment by soomtong** [comment]
+1

**Comment by xchans** [comment]
+1

**Comment by pcandme** [comment]
+1

구름 입력기를 주력 사용 중인 입장에서 이것은 치명적이군요; ㅠㅜ; 맥 기본 입력기를 사용할 의향이 없기 때문에 당분간은 하루패드 사용을 보류해야 할 것 같습니다. 개발자 님 바쁘시겠지만 구름 입력기 문제 해결을 긍정적으로 검토해 주시면 매우 감사드리겠습니다. ^^

**Comment by Canorus** [comment]
+1

**Comment by rhiokim** [comment]
구름 입력기 최신 버젼에서 수정되어 이슈 종료합니다.
입력기 개발자인 정윤원님께 심심한 감사를 전합니다. :-)

**Comment by soomtong** [comment]
현재 버전 (구름 1.8.9c) 점검 확인 결과 말씀 드립니다.

각 줄의 첫 글자 조합에서만 문자가 안나오는 상태입니다. 입력기 조합이 완성되었다고 처리된 이후에 문자가 생성됩니다.

두번째 문자 다음으로는 정상적으로 출력됩니다.

![1st-char](https://cloud.githubusercontent.com/assets/906974/6750597/6a9186ec-cf3f-11e4-8eb3-5aaa628264f8.gif)
