### ISSUE TITLE
print to PDF error

### ISSUE THREAD

**Issue by towserchen** [rhiokim/haroopad#222]
Windows XP
not install Adobe PDF and click print will be a error.The alert windows cannot be close.

**Comment by rhiokim** [comment]
Sorry. Haroopad do not perfectly support to Windows XP.

Recommend! Install Free Virtual Image Print Driver
- http://code-industry.net/imageprinter.php - ImagePrinter Free

**Comment by rhiokim** [comment]
@towser451 Solved?
