### ISSUE TITLE
not resolve relative image path

### ISSUE THREAD

**Issue by youxiachai** [rhiokim/haroopad#227]
in v0.9.0

like this 

`![I/O](./figures/03/block_io.png)`  in view not show the image

but, in v0.8.0 not this problem

my: env:
os: win 7 x86_64
haroopad: v0.9.0

**Comment by rhiokim** [comment]
Oops. this is mistake.
It was hot-fixed v0.9.1

thanks report.

**Comment by auval** [comment]
Hi, thank you for the great software!
relative link seem to work only in the view panel, but **export -> HTML** replaces the relative path with the local pc path. And **export -> Styled HTML** does nothing. (UBUNTU 16.04).

From the commit history I see that the hotfix was committed to gh-pages branch, but was never merged into the develop branch.
