### ISSUE TITLE
[문의] 마크다운 문법에서 체크박스는 지원하지 않나요?

### ISSUE THREAD

**Issue by changhwa** [rhiokim/haroopad#228]
github에서는 list 에 한해서 체크박스를 지원하고 있는걸로 알고 있습니다. 
`- [ ] this is an incomplete item`  이런형태일 때 체크박스를 지원하는것으로 알고 있는데요
혹시 haroopad에서는 아직 도입이 되지 않았는지요?
마크다운으로 이메일을 작성하기 시작하다보니 체크리스트를 만드는 부분에 있어
조금 불편하거 같습니다.

**Comment by rhiokim** [comment]
하루패드의 1차 목표(1.0 버젼까지)는 기존 워드 프로세스의 경험 일부와 모던한 마크다운 에디팅을 위한 특징과 확장성을 실현 하는데 목표를 두고 있습니다.

해당 기능은 사용자 니즈의 변화에 따라 고려해보도록 하겠습니다.

(저도 필요한 기능이긴 해요. 하지만 우선 순위가 매우 낮습니다. ^^;)

**Comment by rhiokim** [comment]
http://haroopad.userecho.com/topic/363163-github-flavored-markdown-task-lists-addition/

**Comment by rhiokim** [comment]
Close

ref #19
