### ISSUE TITLE
How to use syntax highlighting

### ISSUE THREAD

**Issue by zhoulike** [rhiokim/haroopad#229]
I found that one of main features of haroopad is **Syntax Highlighting**, but syntax highlighting doesn't work for me. Why?
![example](https://dl.dropboxusercontent.com/u/22403480/no.png)

**Comment by rhiokim** [comment]
produce on v0.9.1 ?
and is it same with other theme ?

**Comment by zhoulike** [comment]
I test it on v0.9.1, it's OK! This is the problem of v0.9.0. Please close this issue.

**Comment by alexandre-mbm** [comment]
I produce with the v0.11.1 on Ubuntu 10.04.4 LTS. Would be missing some dependency?

**Comment by alexandre-mbm** [comment]
Today It works. I don't know what I did. I did very updates in the Ubuntu recently.
