### ISSUE TITLE
[TOC] redesign table of content

### ISSUE THREAD

**Issue by rhiokim** [rhiokim/haroopad#233]
ref
- http://diveintohtml5.info/

**Comment by changhwa** [comment]
Evernote가 다음과 같은 이유로 노트를 보낼 수 없습니다:

이메일로 보낸 노트가 전송되었으나 처리 중 내부 오류가 발생했습니다. 나중에 노트 보내기를 다시 시도해주십시오.

원본 메시지 정보:
발신: Rhio Kim &lt;notifications@github.com&gt;
수신: changhwaoh.ff04274@m.evernote.com
전체 수신: rhiokim/haroopad &lt;haroopad@noreply.github.com&gt;
제목: Re: [haroopad] [TOC] redesign table of content (#233)

과도한 이메일 수신을 막기 위해 다음 360분 동안 오류 메시지를 받지 않도록 설정 가능합니다.
- Evernote 팀
