### ISSUE TITLE
Vim mode copy and paste does not work correctly

### ISSUE THREAD

**Issue by myrtleTree33** [rhiokim/haroopad#235]
Selecting text using `v` and pasting using `p` copies extra character after selection.

e.g.

```
selected 'hel' using 'v'
 |
***
hello world


pasted 'hel' using 'p' but becomes 'hell'
extra trailing character pasted
  |
hell
```

**Comment by rhiokim** [comment]
This is the same user experience on vim. However, this difference is highlighting the cursor at visual mode (`v`)
We won't fix. sorry
