### ISSUE TITLE
syntax highlighting has some problems

### ISSUE THREAD

**Issue by zhoulike** [rhiokim/haroopad#238]
If i insert "#include <stdio.h>" into the code, syntax highlighting is lost in the following text. 
![no hightlighting](https://dl.dropboxusercontent.com/u/22403480/haroopad-nohighlighting.png)

However, I open this .md file with sublime-text2, the syntax highlighting is OK!
![sublime](https://dl.dropboxusercontent.com/u/22403480/markdown-sublime.png)

Finally, I find this problem is caused by '<'. see below
![highlighting](https://dl.dropboxusercontent.com/u/22403480/haroopad-highlighting.png)

So, is this the problem of haroopad? I'm using v0.9.1.

**Comment by zhoulike** [comment]
Yes. The problem is still here.

2014/1/7 Rhio Kim notifications@github.com

> Reproduce on v0.10?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rhiokim/haroopad/issues/238#issuecomment-31736132
> .

## 

Like Zhou

Cluster and Grid Computing Lab
Services Computing Technology and System Lab
School of Computer Science and Technology
Huazhong University of Science and Technology
Wuhan, 430074, China

**Comment by rhiokim** [comment]
It'll be fixed with next release.
