### ISSUE TITLE
equals and minus characters different width if followed by space

### ISSUE THREAD

**Issue by SamHasler** [rhiokim/haroopad#242]
In the code editor, if you create a heading using the equals `=` or minus `-` characters they will be different widths if followed by a space

``` markdown
123456789
=========
123456789
---------
123456789
========= 
123456789
--------- 
```

The first two headings have nine = or - with no space.

The last two headings have nine = or - and are followed by space,

In Haroopad's code editor the first two are wider than the heading.

**Comment by rhiokim** [comment]
parent : #282
