### ISSUE TITLE
[Q] How can I remove this app. from my mac completely including remove some configuration or temp files?

### ISSUE THREAD

**Issue by ykim0630** [rhiokim/haroopad#248]
How can I remove this app. from my mac completely including delete some configuration or temp files?
After forced termination because this app freeze by unknown reason, I opened it again.
It displayed 'Restored' window, then freeze... again T.T

어떻게 완전히 프로그램 지우나요? 그냥 응용프로그램 폴더 내에서 파일만 삭제하면 안되는 건가요?
재설치해도 Restored 창이 뜨면서 또 멈추네요..
다른 곳에 저장을 하나요? 위치 알려주세요...

**Comment by andrwj** [comment]
Here is the list of installed & created file:

/Applications/haroopad.app
/Users/your-user-id/Library/Application Support/haroopad
/Users/your-user-id/Library/Preferences/com.haroopress.pad.plist
/Users/your-user-id/Library/Saved Application State/com.haroopress.pad.savedState
/private/var/db/BootCaches/*/app.com.haroopress.pad.playlist

*note1: `your-user-id` is account name on your mac.

**Comment by ykim0630** [comment]
thanks :) I hope haroopad is the best md editor!

**Comment by rhiokim** [comment]
@andrwj Exactly!
Closed
