### ISSUE TITLE
Renewal Preference Window

### ISSUE THREAD

**Issue by rhiokim** [rhiokim/haroopad#257]

**Comment by SamHasler** [comment]
If you have time, a way to quickly change the editor font would be helpful.
1. I might have been able to fix #269 myself it there was a font preference
2. Programmers can have a [favourite font](http://www.slant.co/topics/67/~what-are-the-best-programming-fonts) for working with, so a way to quickly set it up would make them feel at home in the editor straight away.

**Comment by rhiokim** [comment]
@SamHasler You can change font and style at "editing area" & "viewer" using css.
1. Exec haroopad
2. Open preference window
3. Click editor tab or viewer tab
4. Click edit button in 'Your style' section
5. Edit your style & Import your local font using css
6. Save to your css file. e.g) MyStyle.css
7. Click reload button
8. Select your style.

**Comment by SamHasler** [comment]
1. Open Notepad
2. Open Font Dialog (Format > Font)
3. Select Font

replace notepad with any other text editor and it would be much the same.

**Comment by rhiokim** [comment]
I know.
But Haroopad is not the native application. This is web-based application that can not access system font & dialog.
