### ISSUE TITLE
Italian Keyboard problem on #

### ISSUE THREAD

**Issue by ghost** [rhiokim/haroopad#258]
On Italian keyboard **\* shortcut is mapped over # key.

**Comment by rhiokim** [comment]
parent : #297

**Comment by Fire-Dragon-DoL** [comment]
Yea I confirm, big issue, can't use it at all on windows, on linux this issue is not present (but I use the same keyboard), probably because altgr is considered a different key

**Comment by rhiokim** [comment]
@valdoweb, @Fire-Dragon-DoL 

`AltGraphKey` key code is 65406 ?

**Comment by rhiokim** [comment]
ref
- http://en.wikipedia.org/wiki/AltGr_key
- key event test - http://guac-dev.org/pub/tests/key-event-test.html
- http://www.w3.org/TR/DOM-Level-3-Events/#key-AltGraph
- https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent?redirectlocale=en-US&redirectslug=DOM%2FKeyboardEvent#initKeyboardEvent()

**Comment by ghost** [comment]
I think it's a combination of ALT and CTRL  . Give two codes at same time: 17 and 18.

**Comment by rhiokim** [comment]
@valdoweb OK Thanks. We'll be fixed with next release.
But we don't have test environments. Can you test for perfect solving this issue?
Please send email to me (rhio.kim [at] gmail.com) with your operating system info.
