### ISSUE TITLE
option to keep syntax highlighting only for code, not pre blocks

### ISSUE THREAD

**Issue by nschneid** [rhiokim/haroopad#260]
On GitHub, indented blocks are preformatted but not syntax-highlighted:

```
function a() and $b
```

...while fenced code blocks with a specified language do trigger syntax highlighting:

``` php
function a() and $b
```

In Haroopad v. 0.9.1 I cannot figure out how to emulate this behavior (code themes apply to both kinds of blocks).

**Comment by rhiokim** [comment]
It'll be fixed in the next version
