### ISSUE TITLE
ubuntu libraries dependency error

### ISSUE THREAD

**Issue by askagirl** [rhiokim/haroopad#265]
```
/usr/share/haroopad/haroopad: error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory
```

fixed by this command on ubuntu saucy 64bit

```
sudo ln -sf /lib/x86_64-linux-gnu/libudev.so.1 /lib/x86_64-linux-gnu/libudev.so.0
```

see this link : http://askubuntu.com/questions/288821/how-do-i-resolve-a-cannot-open-shared-object-file-libudev-so-0-error

**Comment by rhiokim** [comment]
@askagirl I appreciate.

#### more information
- http://haroopad.userecho.com/topic/226287-linux-ubuntu-1304-amd64-occur-error-shared-libraries/
- https://github.com/rogerwang/node-webkit/wiki/The-solution-of-lacking-libudev.so.0
