### ISSUE TITLE
Latex equations are not being rendered properly

### ISSUE THREAD

**Issue by prateek-khandelwal** [rhiokim/haroopad#270]
Here, the comparison, 

equation used - `\int_0^4 x^2 dx` 

![real_eqn](https://f.cloud.github.com/assets/1117050/1806678/b226ed80-6cb7-11e3-9e9f-77ef6c34fd61.png)
![haroopad_eqn](https://f.cloud.github.com/assets/1117050/1806680/b5fe0b8c-6cb7-11e3-9a65-e9ca95ff46b7.png)

_(also, please verify if it is just the case on my system, or is it a known issue)_

**Comment by rhiokim** [comment]
Please test on here. Haroopad is based MathJax.

```
$$
\int_0^4 x^2 dx
$$
```
- http://cdn.mathjax.org/mathjax/latest/test/sample-dynamic-2.html

**Comment by prateek-khandelwal** [comment]
Yes, it renders properly on the web page, but not on haroopad. is it a known issue ?

**Comment by rhiokim** [comment]
No. It's not a known issue.

**Comment by rhiokim** [comment]
does 0.11.1 works well for you?

I guess that is default font issue in Haroopad on your system.
You can change font and style at "editing area" & "viewer" using css.
1. Exec haroopad
2. Open preference window
3. Click editor tab or viewer tab
4. Click edit button in 'Your style' section
5. Edit your style & Import your local font using css
6. Save to your css file. e.g) MyStyle.css
7. Click reload button
8. Select your style.
