### ISSUE TITLE
# on first line code block become a title

### ISSUE THREAD

**Issue by ldez** [rhiokim/haroopad#273]
This block is interpreted as a title while it is a block of code (sh).

```
#!/bin/sh
#
```

**Comment by andrwj** [comment]
If the line is located in the top of file, it denotes `shell script` file and means you are trying to use Haroopad as source editor, isn't it ? ;-)
Haroopad is a Markdown editor, not for `general purpose editing`. 

If you want to contain code block in your file, you can use `code block` syntax.

**Comment by ldez** [comment]
Sorry but no, I'm not trying to use Haroopad as source editor, I don't speak of top the file, I speak of a block of code contain in a text file (I'm writing a tutorial).

I explained the problem poorly.

A block of code in [Markdown Standard](http://daringfireball.net/projects/markdown/syntax) each lines start with one tab.

But in Haroopad, if the first line, of a code block, is starting with a `#` this line is interpreted as a title.

```
#!/bin/sh
#
```

As example, this comment and my first, in their entirety, work on GitHub but does not work with Haroopad.

![haroopad - capture](https://f.cloud.github.com/assets/5674651/1819826/2275b530-70b4-11e3-81a6-dd90a4eb7022.PNG)

**Comment by andrwj** [comment]
You are right, it is a bug. 
Until it is solved, please use triple-backquote for code block. 

Thank you for reporting ;-)

**Comment by rhiokim** [comment]
@ldez 
fixed on v0.11.0
does 0.11.0 works well for you?

**Comment by ldez** [comment]
@rhiokim 
yes works well, good job.
