### ISSUE TITLE
TOC starts with "TABLE OF CONTENTS" (en-us) string in v 0.11

### ISSUE THREAD

**Issue by aprilix** [rhiokim/haroopad#296]
in version 0.11, [TOC] renders in text starts with string "Table of contains".
So I can't use TOC now if i want write document on clear Russian, or other language.

**Comment by rhiokim** [comment]
"Table of Contents" removed in TOC's Header.
It'll be fixed with next release.

**Comment by aprilix** [comment]
thanks :)
