### ISSUE TITLE
how to change language v0.11.0?

### ISSUE THREAD

**Issue by youxiachai** [rhiokim/haroopad#299]
I found haroopad already support chinese, but I can't find where setting language.

**Comment by rhiokim** [comment]
Haroopad does work based on system locale(language).

**Comment by youxiachai** [comment]
@rhiokim but v0.11.0 not work  well, it although show English, but v0.10 work right

**Comment by rhiokim** [comment]
@youxiachai Haroopad does work base on system locale and [languages pack](https://github.com/rhiokim/haroopad-locales)

**Comment by rhiokim** [comment]
Do you want to set the Chinese on v0.11?

Please check your `window.navigator.language` using chrome borwser.
And tell me your OS.

**Comment by rhiokim** [comment]
This is my big mistake. will be fixed with next release.

**Comment by claudiojs** [comment]
I would be nice to let the user set the language himself. _I've got that duplicating and renaming the locale I want to use inside the folder `\.locales`._

**Comment by adaam** [comment]
@claudiojs  How did you do that? change the language for this program.

**Comment by claudiojs** [comment]
Hi @adaam, here are the steps:
- Open the folder C:\Program Files (x86)\Haroo Studio\Haroopad\Libraries.locales;
- Rename the folder of your system language to something like "-bak" (just for precaution);
- Duplicated the folder "en" and rename it to your system language.
