### ISSUE TITLE
Next line before bold as element of a list

### ISSUE THREAD

**Issue by ldez** [rhiokim/haroopad#307]
If a line begins with a bold word and ends with another word in bold, the next line is considered as an element of a list.
Works also with one Word.
When you press on "Enter" next line start with asterisks.

![haroopad bug 02](https://f.cloud.github.com/assets/5674651/2241439/4902ef52-9cd2-11e3-9e3a-047ccfd0ab2b.PNG)

![haroopad bug 02-1](https://f.cloud.github.com/assets/5674651/2241510/95198d12-9cd5-11e3-872d-b184918301ae.PNG)

**Comment by rhiokim** [comment]
I think that is work fine. Why don't using **GFM Line Break** option in preference window?

**Comment by ldez** [comment]
The problem is in the **editor view** not in the viewer.
When I write a word in bold I do not want to make a list, or when I write a word in bold the next line begins with an asterisk as if I was about to write a list.

**Comment by rhiokim** [comment]
Ah~ This is known issue. indent & continue markdown list problem at new line.
This is codemirror issue. - http://codemirror.net/mode/markdown/index.html

It'll be fixed with next release.
