### ISSUE TITLE
Fancy at menu Edit

### ISSUE THREAD

**Issue by alexandre-mbm** [rhiokim/haroopad#323]
![haroopad-edit-menu-issue](https://f.cloud.github.com/assets/957501/2459530/1889e7de-af5d-11e3-8b90-c29501d2edcf.png)

**Comment by rhiokim** [comment]
I want it. but is not possible at now. because of technical issue.

**Comment by alexandre-mbm** [comment]
Do you mean "impossible"?

**Comment by rhiokim** [comment]
@alexandre-mbm Yes. it is not possible.

**Comment by alexandre-mbm** [comment]
And as [tooltip](https://jqueryui.com/tooltip/)?

**Comment by rhiokim** [comment]
@alexandre-mbm :+1: with next release.
