### ISSUE TITLE
strange preview with <i></i>

### ISSUE THREAD

**Issue by fugo** [rhiokim/haroopad#329]
If I use in haroopad this: `## <i class="fa fa-chevron-right"></i> New Headline` the live preview looks strange, my other editor has not this problem

![haroopad](https://cloud.githubusercontent.com/assets/469222/2552950/b14ad0fc-b69f-11e3-9fae-b86a9ee2aa2a.jpg)

**Comment by rhiokim** [comment]
It'll be fixed with next release (v0.12)
Thanks reporting :-)
