### ISSUE TITLE
haroopad won't start for the second time

### ISSUE THREAD

**Issue by c02y** [rhiokim/haroopad#346]
platform:  Ubuntu 14.04

source: both the deb file and binary tar file

After I install it, launch it for open a Markdown file, make some config in the preference, quit the app, then try to reopen the app, and it won't start from neither click the icon or terminal, nothing shows, no message or popup window. 

At first,  I thought it was the problem the configuration I made(which is an apparently a bug), I delete the config dir, and reopen it, it did open, and then open a md file, close it, it won't launch again, same result.

This app is really good, hope you can fix this bug..

**Comment by bryanjhv** [comment]
I have same problem using Ubuntu 12.04 x86.
If you see in System Monitor, haroopad is running, but no UI is displayed...

**Comment by etiennelb** [comment]
Same problem using Ubuntu 12.04 or Arch :

```
[30092:0519/110529:INFO:CONSOLE(607)] "Uncaught TypeError: Expecting a function in instanceof check, but got function (format) {
                return this.lang().months(this, format);
            }", source: /usr/share/haroopad/Libraries/.node_modules/moment/moment.js (607)
```

Maybe a Locale problem ?

**Comment by etiennelb** [comment]
Workaround : use `File -> Close` instead of quitting directly (`File -> Quit`).
There is a problem if Haroopad is exited with a file opened :(

**Comment by rhiokim** [comment]
@codychan, @bryanjhv I found out exactly problem about this issue.

Please don't use `File > quit` menu item for exiting Haroopad. It is node-webkit issue.

**Work**
1. Execute Haroopad
2. use `File > close`, `Ctrl + q` or click close(x) button in Haroopad Box(window) for exit.

**Not Work**
1. Execute Haroopad
2. use `File > quit` for exit.

I'll have fixing with node-webkit for few days about this problem. :-)

**Comment by etiennelb** [comment]
Thank you @rhiokim :)

**Comment by fir2w** [comment]
my Ubuntu 14.04, start for the second time: 

(haroopad:7681): GLib-GIO-CRITICAL **: g_dbus_connection_get_unique_name: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
[7681:0523/130129:INFO:simple_index_file.cc(397)] Simple Cache Index is being restored from disk.
[7681:0523/130130:INFO:CONSOLE(607)] "Uncaught TypeError: Expecting a function in instanceof check, but got function (format) {
                return this.lang().months(this, format);
            }", source: /usr/share/haroopad/Libraries/.node_modules/moment/moment.js (607)

**Comment by bryanjhv** [comment]
Thank you too @rhiokim. I tried Haroopad using now Ubuntu 14.04 x64 and the error was about libudev.so.0 but that's fixed :)

**Comment by rhiokim** [comment]
It'll be fixed with next version.
