### ISSUE TITLE
하루패드 에디터창을 닫았을때 앱 자체는 살아 있으면 좋겠네요

### ISSUE THREAD

**Issue by insanehong** [rhiokim/haroopad#355]
다른 에디터류의 애플리케이션은

에디창이 닫혀도 앱자체는 살아 있기 때문에 

현재 열린 창을 정리차원에 닫고서 

새파일을 열려고 한다거나 기존 파일을 오픈는 등의 처리가 가능

아래 영상 링크 참조

http://www.youtube.com/watch?v=BXfgG7T-Au4&feature=youtu.be 

> 초반에 화질은 몇초후 복귀 되니 참고

**Comment by rhiokim** [comment]
- 편집 후 저장하지 않는 상태에서 윈도우 x 버튼 클릭으로 저장 대화상자 없이 닫히는 오류도 있네요.
- 맥의 경우 윈도우가 없더라도 인스턴스는 존재한 상태로 재 실행이 가능하도록 개선.

**Comment by soomtong** [comment]
:+1: 
제 경우 파일이 수정상태가 아닌데(즉, 모든 파일을 저장했을 때) cmd+q 로 종료하고 하루패드를 재 기동하면 리스토어 파일이 뜹니다.
cmd+w 로 종료(모든 창을 닫게 되기 때문에 종료가 됨)한 후 재 기동하면 정상적으로 빈 파일이 오픈됩니다.

**Comment by rhiokim** [comment]
- /rogerwang/node-webkit/issues/430

**Comment by rhiokim** [comment]
0.13.0 에 해결될 예정입니다.
