### ISSUE TITLE
Misspelling in the markdown section of preferences

### ISSUE THREAD

**Issue by djmittens** [rhiokim/haroopad#356]
Hi, i just installed haroopad and as i was messing around with it i found a misspelling in the markdown portion of preferences  where it says `Use Github Flavord Markdown Table` i am assuming that was intended to be `Flavored`.

This is in the version from the official download page on a mac.
So far however the product has been great!

**Comment by rhiokim** [comment]
@djmittens  Thanks. :-)
It'll fixed with next release.

**Comment by djmittens** [comment]
Hey i was just curious where was the change made i did not see any of the localization/ packaging code in this repository i could have made a pull request for this myself.
