### ISSUE TITLE
뷰모드 저장 기능

### ISSUE THREAD

**Issue by soomtong** [rhiokim/haroopad#358]
건의 사항인데요. 안되면 어쩔수 없습니다.

디폴트로 뷰모드가 (에디터:뷰어) 인데

경우에 따라 뷰모드만 쓰는 사람, 에디터 모드만 쓰는 사람들이 있을 수 있다고 봅니다.
옵션으로 또는 최종 세팅이 저장되는 기능이 있었으면 좋겠어요.

급한 사항은 절대 아닙니다.

**Comment by rhiokim** [comment]
ref - http://haroopad.userecho.com/topic/352513-command-line-options/
- Perspective Features
  - Split Horizontally
  - Split Vertically

**Comment by rhiokim** [comment]
v0.12.1 에서 cli 기능을 통해 뷰 모드로 띄우기 에디트 모드로 띄우기는 제공할 계획입니다. (저장은 안됨)
