### ISSUE TITLE
cannot start haroopad on Ubuntu 14.04 64bit

### ISSUE THREAD

**Issue by xguntis** [rhiokim/haroopad#359]
this is what i get if starting from terminal `haroopad`:

> /usr/share/haroopad/haroopad: error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory

this is what i found when googling on libudev.so.0:

[software installation - How do I resolve a "Cannot open shared object file libudev.so.0" error? - Ask Ubuntu](http://askubuntu.com/questions/288821/how-do-i-resolve-a-cannot-open-shared-object-file-libudev-so-0-error)

The `sudo apt-get install libudev0:i386` is not working because this package was removed from Ubuntu in 14.04.

What is the right solution/workaround to this?

**Comment by rhiokim** [comment]
You can get more information
-  https://github.com/rhiokim/haroopad/issues/265
