### ISSUE TITLE
Can't export PDF

### ISSUE THREAD

**Issue by eailfly** [rhiokim/haroopad#364]
I use haroopad on openSUSE, I download "Linux Binary (64bit)" and decomprossion it to my /usr , now I can use it almost perfect, the only problem is it seem can't export PDF, I can export HTML with or without style, but not PDF, is is not support it now? or I install it wrong way?

**Comment by rhiokim** [comment]
Did you install Adobe Acrobat Reader on your system?
PDF features is depend on **Adobe Acrobat Reader**

**Comment by eailfly** [comment]
Reader？or Acrobat? It seems on linux only have Adobe Reader, Acrobat don't have linux version.

**Comment by rhiokim** [comment]
If you can exporting PDF using Chrome Browser on your system, Haroopad is too.
This feature is implemented in the same way as Chrome

Could please test on your Google's Chrome browser?

**Comment by eailfly** [comment]
ok, I will try it.

**Comment by eailfly** [comment]
I can print MD to PDF with cups-pdf now, thank you for your patience.
