### ISSUE TITLE
Haroopad doesn't start on Ubuntu 14.04

### ISSUE THREAD

**Issue by shockme** [rhiokim/haroopad#371]
Thanks for making a cross platform app that is also very useful!

Unfortunately it doesn't start for me on Ubuntu 14.04 because it links against libudev.so.0 and Ubuntu 14.04 uses libudev.so.1.

The error I'm getting is:
$ haroopad 
/usr/share/haroopad/haroopad: error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory

**Comment by rhiokim** [comment]
You can get more exactly information about this issue.
- https://github.com/rogerwang/node-webkit/wiki/The-solution-of-lacking-libudev.so.0

**Comment by rhiokim** [comment]
@shockme  Does it work for you?

**Comment by shockme** [comment]
@rhiokim, Yes it works, thank you!
