### ISSUE TITLE
Strange Syntax Highlighting - v0.12.0 on OSX 10.9 

### ISSUE THREAD

**Issue by MWers** [rhiokim/haroopad#373]
I'm seeing strange syntax highlighting in code blocks in both the editor and viewer. Here's an example:

![untitled__edited_](https://cloud.githubusercontent.com/assets/808995/3664722/ae6e5be2-11df-11e4-98d0-8ee365ab45ba.png)

And here are my settings:

General:

![preference](https://cloud.githubusercontent.com/assets/808995/3664760/dfb58d24-11df-11e4-9421-501a9f01507f.png)

Editor:

![preference](https://cloud.githubusercontent.com/assets/808995/3664766/e7b736b2-11df-11e4-8708-350f3ead0402.png)

Viewer:

![preference](https://cloud.githubusercontent.com/assets/808995/3664771/ef0b90fc-11df-11e4-9940-1264e4439ad5.png)

Code:

![preference](https://cloud.githubusercontent.com/assets/808995/3664775/f6122b86-11df-11e4-9ab4-c13c6f8eceea.png)

**Comment by rhiokim** [comment]
Haroopad does not support syntax highlighting for all programming languages. 
It depend on highlight.js, Sorry. We don't want to fix.
