### ISSUE TITLE
Error while loading shared libraries: libudev.so.0

### ISSUE THREAD

**Issue by alwaysanirudh** [rhiokim/haroopad#375]
OS: Ubuntu 14.04
Install: 64 bit .deb package.

Post Installation when I try to run the application

Expected Behaviour: The Haroopad editor should start

Actual Behaviour: 
The application exits with an error  "/usr/share/haroopad/haroopad: error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory"

**Comment by rhiokim** [comment]
You can get more information about libudev.so.0 issue.
- https://github.com/rhiokim/haroopad/issues/359
- https://github.com/rhiokim/haroopad/issues/265

**Comment by alwaysanirudh** [comment]
This works for me fine. But the installation should take care of this on its own.

**Comment by rhiokim** [comment]
@alwaysanirudh Thanks.
It will be further improved in upcoming version.

``` bash
#!/bin/bash
paths=(
  "/lib/x86_64-linux-gnu/libudev.so.1" # Ubuntu, Xubuntu, Mint
  "/usr/lib64/libudev.so.1" # SUSE, Fedora
  "/usr/lib/libudev.so.1" # Arch, Fedora 32bit
  "/lib/i386-linux-gnu/libudev.so.1" # Ubuntu 32bit
)
for i in "${paths[@]}"
do
  res=$(echo $i | sed "s/so.1/so.0/g")
  if [ -f $i ]
  then
    ln -sf "$i" "$res"
    break
  fi
done
```
