### ISSUE TITLE
mathcal font support

### ISSUE THREAD

**Issue by macks22** [rhiokim/haroopad#383]
Certain mathematical symbols cannot be expressed in MathJax without using special font styling. In particular, expressing the symbol for _likelihood_ requires this:

$$\mathcal{L}(\theta|y)$$

However, it seems the mathcal font and other fonts in Haroopad simply render to a non-stylized font.

![likelihood-symbol-rendering](https://cloud.githubusercontent.com/assets/3409997/3755649/f08d1e80-1826-11e4-82b6-ced74eb16364.png)

**Comment by macks22** [comment]
See [here](http://meta.math.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference) for an example of the various fonts which should be supported.

**Comment by rhiokim** [comment]
It is working perfectly on my Mac 10.9.4 :)

![screen shot 2014-08-02 at 4 29 23 am](https://cloud.githubusercontent.com/assets/145777/3783925/419b9752-19b2-11e4-95f6-0b561c987256.png)

Could you please tell me about your platform?

**Comment by macks22** [comment]
Ubuntu 12.04 LTS

**Comment by macks22** [comment]
Also, I'm running `node.js v0.10.30`.

**Comment by rhiokim** [comment]
It'll be support with next release.
