### ISSUE TITLE
support for \left and \right parens in math mode

### ISSUE THREAD

**Issue by macks22** [rhiokim/haroopad#384]
Use of \left and \right in math mode allows insertion of "smart" parentheses around larger equations. In contrast to normal parens, which are the same height regardless, the \left( and \right) parens scale to the height of the equation. Currently these symbols render as normal parens.

![left-right-parens-haroopad](https://cloud.githubusercontent.com/assets/3409997/3756176/0a491734-182c-11e4-94d6-261dd625f438.png)

**Comment by rhiokim** [comment]
It'll be support with next version.
