### ISSUE TITLE
Won't launch in elementary OS

### ISSUE THREAD

**Issue by Gabriel-p** [rhiokim/haroopad#386]
Installed [32 bit version](https://bitbucket.org/rhiokim/haroopad-download/downloads/haroopad-v0.12.2-i386.deb) in elementary OS 0.2 (based on Ubuntu 12.04) and the app refuses to launch.

Running from terminal returns:

```
/usr/share/haroopad/haroopad: error while loading shared libraries: libudev.so.0: cannot open shared object file: Error 40
```

**Comment by rhiokim** [comment]
You can get information about this. - https://github.com/rhiokim/haroopad/issues/265
