### ISSUE TITLE
opps app is crash

### ISSUE THREAD

**Issue by a555521** [rhiokim/haroopad#388]
When I try to open a .md file by double clicking it, it always shows "opps app is crash".
No issue when I open harropad first and then open the file.

I'm using win 8.1

**Comment by robbielj** [comment]
yep, i have the exactly same issue on win7 as well. Cannot find any clue for solving.

**Comment by OvOwl** [comment]
Probably due to spaces in your filename? Same was the problem here. In Linux it just opens an empty document instead. Should be easy to fix.

**Comment by robbielj** [comment]
No. There is no space in the filename.

edit: I have conducted a little more research. This issue seems to occur only when parent folder has  space in its name. Thanks for the hint, @OvOwl

**Comment by rhiokim** [comment]
It is fixed at v0.13.

**Comment by user4815162342** [comment]
Are you certain this is fixed? I'm still having this problem, and I seem to be running 0.13.0 (When I check for updates, it says that I'm up to date). I'm using this on linux, and in my case trying to open a filename with spaces just opens up an empty file, as @OvOwl says.
