### ISSUE TITLE
Local images

### ISSUE THREAD

**Issue by sebelk** [rhiokim/haroopad#389]
It's there a way to insert a local image and can be exported to a pdf and that is not broken?

Thanks in advance!

**Comment by soomtong** [comment]
can u explain your os, version ?
my osx 10.9 with `haroopad 0.12.2` will print nice image in pdf file. even, that markdown file is not saved in local storage disk.

**Comment by sebelk** [comment]
Hi soomtong,

I've found it worked setting the image absolute path instead the relative
one!

Thanks!

2014-08-11 3:26 GMT-03:00 soomtong notifications@github.com:

> can u explain your os, version ?
> osx 10.9 with haroopad 0.12.2 will print nice image in pdf file. even,
> that file is not saved local storage disk.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rhiokim/haroopad/issues/389#issuecomment-51745689.

## 

## 

Sergio Belkin  http://www.sergiobelkin.com
LPIC-2 Certified - http://www.lpi.org

**Comment by soomtong** [comment]
nice, u can use drag&drop action for image insert. have a nice haroopadding!

**Comment by sebelk** [comment]
thanks!

**Comment by sebelk** [comment]
Sadly, I'm using Fedora 20 and drag&drop write a relative path.... forget it,  now it'seen good, I don't what's wrong, but it works :+1:    :)
