### ISSUE TITLE
First Page and TOC

### ISSUE THREAD

**Issue by sebelk** [rhiokim/haroopad#390]
Hi, When I insert a TOC, the first page looks ugly showing only the header 1 and any text before the TOC. I'd want that TOC inmediately follows the header 1. Is it feasible?

Thanks in advance!

**Comment by rhiokim** [comment]
You can insert `[TOC]` into any line that you want.
Also can align too.

``` markdown
[TOC "float:right"]
[TOC "float:left"]
```
