### ISSUE TITLE
GFM table's column-width issue

### ISSUE THREAD

**Issue by webron** [rhiokim/haroopad#392]
When using GFM's table, sometimes the column width used is not appropriate and even a single word breaks. This is different from how GitHub renders the output.

Check the following sample:

```
Field Name | Type | Description
---|:---:|---
<a name="contactEmail"/>email | `string` | The email address of the contact person/organization. MUST be in the format of an email address.
```

The output looks like this - https://www.dropbox.com/s/f2eixrohl4qelre/Screenshot%202014-08-12%2011.51.01.png - no matter how much space I give to the preview pane.
As you can see, `string` breaks into two lines.

**Comment by rhiokim** [comment]
It'll be fixed with 0.13.0
