### ISSUE TITLE
Command line support

### ISSUE THREAD

**Issue by eungjun-yi** [rhiokim/haroopad#40]
It would be great if Haroopad supports command line arguments.

e.g. `haroopad foo.md`  to open a file or `haroopad --help` to show help message.

**Comment by rhiokim** [comment]
It support on mac.

```
$ open -a "haroopad" --args /path/to/file.md
```

Did not working on your platform(maybe linux)?
And now, there are no plans to support better CLI.

**Comment by eungjun-yi** [comment]
Well, It works with absolute path as you said,

```
$ haroopad /path/to/file.md
```

but not with relative path.

```
$ cd /path/to
$ haroopad file.md
...
[1481:0525/203847:INFO:CONSOLE(338)] "Uncaught Error: ENOENT, no such file or directory 'file.md'", source: fs.js (338)
```

**Comment by eungjun-yi** [comment]
My workaround is writing a shell script to launch haroopad. It works well for both of absolute and relative path.

```
#!/bin/sh
haroopad `realpath $1`
```

**Comment by leodutra** [comment]
C'mon guys... you really closed an important feature like this?
Developers loves to use `editor .` and `editor <filename>`.

**Comment by jisantuc** [comment]
If you don't have `realpath` (I didn't on OS X Yosemite) [this SO question/answer](http://stackoverflow.com/questions/3572030/bash-script-absolute-path-with-osx) is useful, though change the `$0` at the end to `$1`

**Comment by leodutra** [comment]
I use Ubuntu at home and Windows 8 on my workplace.
Haroopad could work across platforms in the same simple way; as Atom.
