### ISSUE TITLE
Odd behavior of reopened files on application restart

### ISSUE THREAD

**Issue by webron** [rhiokim/haroopad#403]
I'm on OSX.

When I cmd+q to quit the up and then reopen it, the files that were opened when the application was closed are reopened as well.

However, the files are reopened with a 'Restored' title, and when I try to save them, the application asks me where to save them (instead of just use the original files and their location).

**Comment by soomtong** [comment]
Hi, i have that situations too on osx. maybe some caches are there, not exactly.
then, i do, quit `haroopad` by `cmd+w`

**Comment by webron** [comment]
Yeah, cmd+w works, but it's unnatural for OSX.
Also, it doesn't give you the effect of reopening the closed files when you start haroopad again, even though you can open from latest history.

**Comment by rhiokim** [comment]
New version is out, Could you please check?

**Comment by webron** [comment]
Well, it doesn't happen anymore, but that's because it doesn't reopen _any_ of the previously opened files. I'm not sure that's the expected/wanted behavior.
