### ISSUE TITLE
Reopening a file does not refresh the file

### ISSUE THREAD

**Issue by eungjun-yi** [rhiokim/haroopad#41]
Reopening a file does not refresh the file even if the file has been modified by other editor.

**Comment by rhiokim** [comment]
known issue :-). It will be fixed in the next version(v0.3.2).

**Comment by eungjun-yi** [comment]
Nice!

**Comment by rhiokim** [comment]
It's change ux.
file open, recently file open -> new window -> file open at new window

It will be deploy with launching version.
