### ISSUE TITLE
Syntax highlight on the preview

### ISSUE THREAD

**Issue by kemelzaidan** [rhiokim/haroopad#410]
I'd like to see the syntax highlight not only on the editor window, but on the preview too.

Thanks and congratulations for the great app! :+1:

**Comment by crokobit** [comment]
+1 thanks :))

**Comment by kemelzaidan** [comment]
![haroopad](https://cloud.githubusercontent.com/assets/897436/4566929/09d6d736-4f2d-11e4-8740-25716d8dd07b.jpg)

Explanation on the image. Please, allow me to know if not clear.

**Comment by rhiokim** [comment]
@kemelzaidan Do you want syntax highlight with fenced code block?
You can add language name with <code>```</code>

<pre>
```<b>html</b>
&lt;!DOCTYPE html>
 ....
```
</pre>

You can more detail information about markdown syntax in Haroopad.
Please references here. "Help > Markdown Syntax Help"

**Comment by kemelzaidan** [comment]
Nope. It's on the preview pane, on the right side. Left pane already shows the syntax highlight on it. Could you understand my request?

**Comment by rhiokim** [comment]
Yes. I know what you want.

![haroopad_410](https://cloud.githubusercontent.com/assets/145777/4747718/f6b2482c-5a60-11e4-8d30-b249ab3d7f04.png)

Please refer it too - https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting

**Comment by kemelzaidan** [comment]
Oh, thanks!

Congratulations for the great app and keep up the good work.

Yes. I know what you want.
