### ISSUE TITLE
Follow and display/edit other markdown files

### ISSUE THREAD

**Issue by mv0** [rhiokim/haroopad#414]
Hello,

More on the side of a wish list: ability to follow and display other markdown files.

I.e.,

```
My thoughts exactly: you can either go to [a](doc/A.md) or to [b](doc/B.md). 
```

Although I can see the links being blue in color, nothing happens when I click on them.

PS: I use the latest Linux version (0.12.2 -- deb package).

**Comment by rhiokim** [comment]
It is available in v0.13.
