### ISSUE TITLE
Feature Request: plantuml diagrams

### ISSUE THREAD

**Issue by cinxgler** [rhiokim/haroopad#415]
Hi,

Would be great to have the chance of adding UML diagrams using plantuml: http://plantuml.sourceforge.net/

**Comment by changhwa** [comment]
+1

**Comment by rhiokim** [comment]
Hi guys
How about https://github.com/knsv/mermaid
Mermaid syntax look like markdown and so make it easy to draw diagram as plantuml
We'll be available in v0.13.0 (coming up)

**Comment by cinxgler** [comment]
Great to have this feature, but  I'm already using plantuml syntax and generators on my documentation and exporting them using http://pykwiki.nullism.com/extensions.html#pykwikiextuml

maybe it could be integrated into haroopad using: 

http://plantuml.sourceforge.net/demojavascript2.html
http://plantuml.sourceforge.net/demojavascript.html

**Comment by rhiokim** [comment]
@cinxgler I think too that plantuml is best solution for diagram work.
But it work on online mode only.  Haroopad is desktop application.  

We can, but must be added so complex codes.
In my case. there are more gains than loss.

Sorry about this.

**Comment by lalebarde** [comment]
plantuml works on the desktop too
