### ISSUE TITLE
UI: Action feedback

### ISSUE THREAD

**Issue by alejandrosantana** [rhiokim/haroopad#421]
This is a desired feature.

When I save a file, I do not see any visible symthom that the action was carried out correctly. Maybe obvious, but in my mind remains a slight doubt of "did it save OK?".
What about a little quick fading sign in the status bar or elsewhere?

**Comment by rhiokim** [comment]
It's already done. :-)

If opened file, Haropoad Title Bar is "Filename"
If edited file, Haroopad Title Bar is "Filename (Edited)"
If saved file, Haroopad Title Bar is "Filename"

**Comment by alejandrosantana** [comment]
Oh, my bad I didn't notice. Too late at night.
Perfect then. +1 to haroopad. :)
