### ISSUE TITLE
RST support

### ISSUE THREAD

**Issue by alejandrosantana** [rhiokim/haroopad#422]
This is a desired feature.

Appart of Markdown, it would be nice to support RST (ReStructured Text). Then it would be not just amazing, but killer.

**Comment by rhiokim** [comment]
I think your suggestion is useful idea. But I don't want to mix with other formats.

PS. I do not want to be complicated programming document by the human using the markdown.

**Comment by alejandrosantana** [comment]
OK, I see the point, just thought it is useful and might be of your interest. Anyway, I understand the idea of not mixing tings. Thanks.
