### ISSUE TITLE
Window 8.1 not supported

### ISSUE THREAD

**Issue by thewashingtonhua** [rhiokim/haroopad#426]
The latest msi file is invalidate on Windows 8.1.

**Comment by tolot27** [comment]
I could install it flawlessly on my Windows 8.1 Professional 64-Bit system. Unfortunately, only a 32 bit msi is available.

**Comment by thewashingtonhua** [comment]
Mine is Windows 8.1 Ultimate. 64-bit. Failed.

**Comment by rhiokim** [comment]
New version is out. please check?
