### ISSUE TITLE
Angle brackets inside block code

### ISSUE THREAD

**Issue by ChristophWurst** [rhiokim/haroopad#428]
Whenever I have C code blocks in my .md files, Haroopad messes up syntax highlighting after angle brackets (e.g. includes):

``````
#Test

##Header 1
...

```C
#include <stdio.h>

int main() {
    printf("Hello\n");
    return 0;
}
```

##Header 2
...
``````

My guess is that the syntax highlighter interprets the angle brackets as HTML tag, however there is (of course) no closing tag.

This is what it looks like:
![screenshot](https://cloud.githubusercontent.com/assets/1374172/4977101/e9c7da42-68ec-11e4-8ef0-3a9229a3e931.png)

I am using v0.12.1 on Arch Linux

**Comment by nykh** [comment]
I have this problem too!

version v0.13.1 on Ubuntu.

**Comment by nykh** [comment]
It gets even more complicated with just inequality (less than "<" especially) I think it is a good idea to disable syntax highlighting inside the code block.
