### ISSUE TITLE
Exact scroll synchronization between editor and previewer

### ISSUE THREAD

**Issue by eungjun-yi** [rhiokim/haroopad#43]
I want previewer always shows the rendered result of a part includes the line which I am editing. But sometimes the previewer does not do that, in particular if the document which I edit is much longer than the height of preview window.

Surely, I know that is **very** difficult. :)

**Comment by rhiokim** [comment]
That's right. 
This problem is very difficult to resolve in a conventional manner.

The long document have performance issues.

So, I'm thinking how to solve the problem in terms of the other.

Perhaps without resolving technically, I will improve the UX.
But now, I have not any idea. :-)

**Comment by eungjun-yi** [comment]
What about allowing users to disable the synchronization?

I think scrolling the preview window manually is good enough for me and better than scrolling it automatically and incorrectly.

**Comment by rhiokim** [comment]
Check this!

http://pad.haroopress.com/page.html#preferences

**Comment by eungjun-yi** [comment]
Wow, there is the option already! Thanks!
