### ISSUE TITLE
Bug report: The file path can't contain space in Windows

### ISSUE THREAD

**Issue by liuhewei** [rhiokim/haroopad#430]
When I open a MD file whose path includes space through double-clicks, it fails (show nothing).

Windows 7, 32 bit.

**Comment by tolot27** [comment]
That happens only, if Haroopad is not running yet. If there is an instance running, the file containing spaces can be opened. But then the short file name (8.3) is shown in the title.

**Comment by rhiokim** [comment]
It'll be fixed with v0.13.0 (coming up)

**Comment by tdebatty** [comment]
Same problem in Linux, with Haroopad 0.13.1
Ubuntu 14.04

**Comment by janv8000** [comment]
I had to change the following registry key: 
`HKEY_CLASSES_ROOT\haroopad\shell\open\command`
## Original
`C:\Users\username\AppData\Roaming\Haroo Studio\Haroopad\haroopad.exe %1`

## Changed (added quotes)
`C:\Users\username\AppData\Roaming\Haroo Studio\Haroopad\haroopad.exe "%1"`
