### ISSUE TITLE
preview Link target

### ISSUE THREAD

**Issue by insanehong** [rhiokim/haroopad#44]
프리뷰 영역의 링크를 클릭하면 쓰던글이 없어지고 링크 페이지로 가버림...

**Comment by rhiokim** [comment]
v0.3.1 / Mac OS 10.8.3 기준으로

기본 설정값은 아무런 반응을 하지 않도록 되었고
Preferences (Cmd+,) 의 Viewer 탭에서 `Make links clickable in Editor view` 를 체크 상태로 할 경우
시스템 기본 브라우저로 새창 띄우도록 되어있어요.

좀더 자세한 재현 시나리오가 필요해요.

**Comment by insanehong** [comment]
ㅎㅎ 얍

2013년 5월 28일 오후 1:54, Rhio Kim notifications@github.com님의 말:

> 기본 설정값은 아무런 반응을 하지 않도록 되었고
> Preferences (Cmd+,) 의 Viewer 탭에서 Make links clickable in Editor view 를 체크
> 상태로 할 경우
> 시스템 기본 브라우저로 새창 띄우도록 되어있어요.
> 
> 좀더 자세한 재현 시나리오가 필요해요.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/rhiokim/haroopad/issues/44#issuecomment-18529508
> .

## 

/*
- @insanehong
  *
- @Name DeokHong Kim
- @Desc Web Developer, Front-end Engineer at NTS
- @Twitter @insanehong http://twitter.com/insanehong
- @Blog incorrect note http://insanehong.kr
- @Return intro957@gmail.com
  */

**Comment by insanehong** [comment]
# environment
- Version : 0.3.1
- Os : OS X 10.8.3
- config : Make links clickable in Editor view 비활성화 상태
- 발생 문제 : preview 의 youtube  링크(sort url 처리된)를 클릭시 에디터 창에서 redirection 이 발생.
- 발생조건 : 링크를 쉬프트 + 클릭 하였음. 그외 링크에서도 동일한 문제 발생
- 링크 syntax : [text](링크주소)

![screen shot 2013-05-28 at pm 2 15 29](https://f.cloud.github.com/assets/1558742/570643/a2cdc1d6-c755-11e2-88a3-97ff65be2ba1.png)

# 테스트 가능한 마크다운코드

```
# Guide to Git for Windows 

이 글은 팀내 ***info Windows OS*** 사용자를 위하여 Git 설치 및 업무환경 세팅에 대하여 사내 위키 문서에 정리해 놓은 내용을 옮겨온 것입니다. 

***info Windows 7*** 을 기준으로 작성 되었으며 GUI 특히 ***info tortoiseSVN*** 에 익숙한 사용자 경험을 원하는 분들을 위하여  
***important TortoiseGit*** 의 설치와 ***important CLI***를 사용하기 원하는 분들을 위한 ***info mysysgit***의 설치 과정을 담고 있습니다.

## TortoiseGit 설치하기
* [다운로드](https://code.google.com/p/tortoisegit/wiki/Download?tm=2)

### 1. 다운로드 페이지 본인 컴퓨터에 맞는 설치 파일을 다운로드 받습니다.

![TortoiseGit 다운로드 페이지](./@img/tor1.jpg)

### 2. 다운로드된 파일을 실행 합니다. 

![TortoiseGit 다운로드 페이지](./@img/tor2.jpg)

### 3. 다음의 예시와 같이 설치를 진행 합니다. 

![TortoiseGit 설치1](./@img/tor3.jpg)

![TortoiseGit 설치2](./@img/tor4.jpg)

![TortoiseGit 설치3](./@img/tor5.jpg)

![TortoiseGit 설치4](./@img/tor6.jpg)

![TortoiseGit 설치5](./@img/tor7.jpg)

![TortoiseGit 설치6](./@img/tor8.jpg)

### 4. 설치가 완료되면 마우스 오른쪽 버튼을 눌러 TortoiseGit 이 제대로 설치 됬는지 확인 합니다. 

![TortoiseGit 설치 확인](./@img/tor9.jpg)

## ssh public key 만들기

***info github***, ***info gitlab***, ***info bitbucket*** 등을 이용하거나 별도로 구축한 원격의 저장소를 이용하기 위해서는 ***important ssh key*** 가 필요합니다. 

이후에 얘기할 ***info msysGit***을 이용하면 몇줄의 ***info commend***info 입력으로 간단하게 만들수 있지만 일단 windows 환경에서 ***important PuTTYgen*** 을 이용하여 만드는 법을 소개 합니다.

### 1. 윈도우 시작 > TortoiseGit 안에 있는 PuTTYgen 을 실행 합니다. 

![PuTTYgen 실행1](./@img/key1.jpg)

### 2. PuTTY Key Generator 실행 화면에서 Generate 버튼을 클릭 합니다.




## 참고 할만한 동영상
* [설치 가이드 영상](http://youtu.be/pp2S2lHjzZI)
```
