### ISSUE TITLE
CLI 에서 렌더링을 제공하지는 않나요?

### ISSUE THREAD

**Issue by changhwa** [rhiokim/haroopad#441]
하루패드가 이제 독자적인 문법들이 있다보니 서버에서 md 파일을 올릴때는 불편함이 있습니다.
혹시 cli로 렌더링이 가능하다면 우분투 서버나 이런 곳에 설치해서 사용하면 좋을 듯 해서 
건의 해봅니다.

잘 쓰고 있어요.

**Comment by rhiokim** [comment]
현재 계획은 하루패드에서 직접 CLI 를 제공하는 방식이 아닌 Hooking, Plugin 등을 통해 API 를 디자인할 계획입니다.

좀더 자세히 설명드리면 직접 post-save-{user-defined-task}.js 이라는 파일에 task 를 정의하고 하루패드에 해당 스크립트를 등록하면 해당 파일이 저장될 때 위의 hook 파일에 현재 작성중인 파일의 데이터 모델(FState, Markdown, HTML 등)을 전달하는 방식입니다.

더불어 여러 방식을 오랫동안 고민중이지만 기본적으로 Haroopad 의 목적은 **Human Writing** 이라서 위와 같은 기술적인 접근을 어떻게 하루패드에 녹여낼지는 좀더 긴 시간이 필요합니다.
