### ISSUE TITLE
Number 6 acts as "insert header 6" (<ctrl+6>)

### ISSUE THREAD

**Issue by AnderRasoVazquez** [rhiokim/haroopad#447]
When I type "6" I get:
`###### 6`
Then, I type again "6" and I get:
`66`
This is what I get when I repeat typing "6":
(1) ###### 6
(2) 66
(3) ###### 666
(4) 6666
(5) ###### 66666
(6) 666666

**Comment by rhiokim** [comment]
@AnderRasoVazquez Thanks for the reporting.
It'll be fixed with next release.

**Comment by cefn** [comment]
I also experience this on Lubuntu 14.10. Is there a version without this bug as it makes Haroopad unusable for most purposes, although I love the app design in every other way. There doesn't seem to be a guide or indication for users to build from source if that's what's needed to workaround this bug.

**Comment by cefn** [comment]
Hi again. Just thought I should note a workaround. If you type your text containing 6 on a new line, or in a different text editor, you can paste it in, without triggering the bug. It's only typing events (hitting the 6 key when the Haroopad window is your focus window) which seems to trigger this.

**Comment by arcr-dev** [comment]
A simple workaround. Type 6 twice and delete the last one.
