### ISSUE TITLE
After Tab key insert, Enter Key Press Bug

### ISSUE THREAD

**Issue by r2fresh** [rhiokim/haroopad#45]
소스를 입력하기 위해 tab키를 입력하고 함수를 입력한 후 다음 엔터키를 입력하면

영역을 빠져나가 버리는 버그가 있네 

아는 내용인가^^

**Comment by rhiokim** [comment]
몰랐던 소소한 이슈네요.

tab 키를 space 로 변경할 계획이에요.
피드백 감사합니다. :-)

**Comment by rhiokim** [comment]
이거 아직도 발생하고 있나요?

**Comment by rhiokim** [comment]
답변이 없으시군요. 일단 이슈 종료합니다.
다시 발생하면 재 등록 부탁드립니다.
