### ISSUE TITLE
I cannot open haroopad in win7

### ISSUE THREAD

**Issue by yf2009017** [rhiokim/haroopad#450]
I can open it first time when installed it, howerver, the application UI doesn't appear when I double click the exe file today, and the process is inside task manager list. I don't know what's the issue, please help me fix it out, Thanks a million..

**Comment by a1880** [comment]
Looks similar to my case: http://haroopad.userecho.com/topic/585810-open-with-spoils-installation-of-haroopad-v013-under-win7/

**Comment by yf2009017** [comment]
How is going now, I find a solution that you can drap a Markdown file to the application for twice, then the interface would appear. However,  I don't think it is a good solution.

**Comment by rhiokim** [comment]
New version is out. v0.13.1 
Could you please check this issue.

**Comment by mtancoigne** [comment]
Seems that it's not fixed : #489 popped in for 0.13.1

**Comment by yf2009017** [comment]
Thanks for fixing, everything looks fine~~

**Comment by rhiokim** [comment]
It'll be fixed with next release
