### ISSUE TITLE
Support YouTube iframes

### ISSUE THREAD

**Issue by AnderRasoVazquez** [rhiokim/haroopad#451]
I write on a blog and sometimes I add YouTube videos but when I insert them on Haroopad via:

`<iframe width="853" height="480" src="//www.youtube.com/embed/ntLPcVAyNPE" frameborder="0" allowfullscreen></iframe>`

A blank space appears. I'm not saying that Haroopad should be able to play those videos (would be nice) but maybe **a rectangular black box with the YouTube logo could look better**.

**Keep up the good work! =)**

**Comment by rhiokim** [comment]
@AnderRasoVazquez Thanks for the reporting. Haroopad is not web site. So `src="//www.you~"` evaluated to local path. In this case you can fix it yourself.

```
<iframe width="853" height="480" src="http://www.youtube.com/embed/ntLPcVAyNPE" frameborder="0" allowfullscreen></iframe>
```

And do you know `@[ ]( )` syntax on the Haroopad?

**Haroopad**

```
@[alt text](original-url "user-defined style")
```

**example**

```
@[Chrome OS Guided Tour](http://www.youtube.com/watch?v=ntLPcVAyNPE "width:853px;height:480px")
```

It is possible with many services. But it only work with Haroopad. :-(

**Comment by AnderRasoVazquez** [comment]
Perfect, thanks for your help ^^
