### ISSUE TITLE
v.0.13.0: ``` ```  area after semicolon(;) press enter next line 'NaN.'

### ISSUE THREAD

**Issue by ihoneymon** [rhiokim/haroopad#452]
Use Haroopad v.0.13.0(OS: ubuntu 14.04 64bit)

typing "``` ```" area, end semicolon(;) and enter press,
then **NaN.**

Like this:

<pre>
```java
@Data
class Source {
    String name;
    String type;
  NaN.  //--- Here
    String createDate;
    String lastModifiedDate;
}
```
</pre>

**Comment by rhiokim** [comment]
@ihoneymon Thanks for the reporting. It is known issue. I'll have plan to release v0.13.1 on this week.
