### ISSUE TITLE
Can't type Chinese on Win7 64bit

### ISSUE THREAD

**Issue by shaochangbin** [rhiokim/haroopad#455]
Steps to reproduce,
- Download and install haroopad 64bit for Win7, 
  https://bitbucket.org/rhiokim/haroopad-download/downloads/Haroopad-v0.13.0-win-x64.msi
- Install Google Pinyin input method.
- Open Haroopad and switch to Chinese input method.
- Try typing any Chinese characters.
- No word is displayed on screen.

**Comment by fbens** [comment]
I also encountered this problem, Chinese can not be displayed.
