### ISSUE TITLE
copy find and paste

### ISSUE THREAD

**Issue by eidng8** [rhiokim/haroopad#457]
On Windows 7, not sure if other Windows version too, select some text, press ctrl+c, then ctrl+f, the ctrl+v. It doesn't paste to the find box, instead pasted to the editing area where the cursor was. Even I manually click the find box with mouse and see the cursor is in the box, pasting still doesn't get it to the find box.

**Comment by rhiokim** [comment]
Thanks for the reporting :-)
It'll be fixed with next release. v0.13.1

**Comment by eidng8** [comment]
Hi, I've installed v0.13.1, the issue still persists.
