### ISSUE TITLE
When  "***" syntax use first string, i have problem.

### ISSUE THREAD

**Issue by insanehong** [rhiokim/haroopad#46]
- Version : 0.3.1
- Os : OS X 10.8.3
- 발생조건 : 라인시작시 강조문 작성을위한 *** 입력.
  _발생 문제 : 강조문 사용을 위해 입력한 \_** 이 line 으로 변경되어 버림. preview 뿐만 아니고 작성영역에서도 라인으로 변경되어 버림

![screen shot 2013-05-29 at am 10 23 20](https://f.cloud.github.com/assets/1558742/576340/5f19c2e2-c7fe-11e2-94d3-88d22e3537fe.png)

```
# 시작에 강조문을 사용하려고 할때의 버그 테스트 가능한 예시

***

위에 생긴 선은 입력창에서 일반 문자열로 시작하지 않고  \*\*\* 를 쓸경우 생겨남
```

**Comment by rhiokim** [comment]
마크다운 표준 참조
 [HORIZONTAL RULES](http://daringfireball.net/projects/markdown/syntax#hr) 

일단 `***` 는 표준은 맞고 다만 하루패드에서 Pair Characters 처리로 자동으로 `**`, `{`, `[` 를 타이핑하면
`]`, `}`, `**` 가 붙게되어 `**`의 경우 `****`가 되면서 에디터 영역에서 자동으로 라인으로 처리해버리는 현상임

불편하면 환경설정 Editor 탭에서

`Auto pair characters` 를 uncheck 상태로 설정하면 됩니다.

사용성 개선은 좀더 숙고후에~

**Comment by insanehong** [comment]
넵 그럼 edite 영역에서 라인으로 처리해 버리는 문제는 이슈로 남고 
preview 여역에서는 변환되는 방향으로 고려해 주세요.

edit 영역에서도 라인으로 변경되어버리면 그뒤로 문자열을 이어갈수가 없어요.

**Comment by rhiokim** [comment]
참고하세요.

Auto pair characters 옵션에 의해서 줄이 생기더라도 편집하는데 문제는 없어요.

줄이 생기더라도 커서 위치는 기억하고 있어서 `**[커서위치]**` 
`**`이던 `***` 이던 그냥 계속 입력하면 `**볼드처리**`, `***볼드처리**` 방식으로 
입력이 되요.

다시 라인이 풀리죠.

**Comment by insanehong** [comment]
음... 그건 haroopad 를 잘알고 있는 사람만 인지 가능한 문제라 

preview 영역에서 변환되는건 당연하다고 느끼지만

editor 영역에서 라인이 생겨버리는건 UX 측면에서 잘못된거 같아요.

Mou 나 Markdown Pro 는 Edit 영역에서 디자인요소에 대한 변경은 일어나지 않고 있어요.
