### ISSUE TITLE
마크다운으로 코드를 작성할때 

### ISSUE THREAD

**Issue by initNirvana** [rhiokim/haroopad#460]
![2015-01-28 1 37 25](https://cloud.githubusercontent.com/assets/6625053/5932531/d8cec0b8-a6f2-11e4-8d88-ad2262e6d326.png)

줄을 바꿧을떄 NaN이 나오네요 

버그가 생기는 조건을 정확히 알아보려 했지만 간헐적으로 생기는것 같습니다. 

사용 환경은 OS X 10.10.1, 하루패드 v0.13.0 입니다.

**Comment by rhiokim** [comment]
이 문제는 곧 출시될 버젼에서 해결될 예정입니다.
