### ISSUE TITLE
Printing spools indefinitely

### ISSUE THREAD

**Issue by rjollos** [rhiokim/haroopad#461]
When printing, the file seems to be sent to the printer but it just displays indefinitely as spooling. I've tried real printers and printing to PDFCreator (version 2.0.2). This is on Windows 7 Ultimate with Haroopad 0.13.

![printdialog](https://cloud.githubusercontent.com/assets/1152089/5945521/e670862a-a6e3-11e4-9616-6183185ea35c.PNG)

Following the suggestion in #318 I tried printing a window in Chrome (version 40). Printing in Chrome works fine. 

Is there anything I can do to generate a debug log?

**Comment by rhiokim** [comment]
New version is out. v0.13.1 
Could you please check this issue.

**Comment by rjollos** [comment]
The issue is resolved with 0.13.1. Thank you.
