### ISSUE TITLE
Can't enter ISO date like 2015-02-06

### ISSUE THREAD

**Issue by spillej** [rhiokim/haroopad#465]
Whenever I start writing the date 2015-02-06

it automatically change the line to

**Comment by spillej** [comment]
I mean

 without comment ;-)

**Comment by a1880** [comment]
This is probably caused by the error reported as issue https://github.com/rhiokim/haroopad/issues/447

**Comment by rhiokim** [comment]
@spillej Yep it's the bug. @a1880 thanks.
It'll be fixed with upcoming version.
