### ISSUE TITLE
Window title bar is only updated on activation (Win7)

### ISSUE THREAD

**Issue by niklasfrykholm** [rhiokim/haroopad#468]
If you make some changes to a document, `(Edited)` does not appear in the title bar. However, if you Alt-tab to another window and Alt-tab back, `(Edited)` appears.

If you save, `(Edited)` doesn't disappear, but Alt-tabbing back and forth fixes it.

Similarly, if you create a new file and save it, the file name does not appear in the title bar until you have Alt-tabbed.

Thus, it seems like the title bar is only updated when the window is activated.

**Comment by rhiokim** [comment]
Does v0.13.1 works well for you?

It's working perfectly for me.
![modified-status](https://cloud.githubusercontent.com/assets/145777/6703161/82291bd8-cd7a-11e4-883f-d1d2983363fd.gif)

**Comment by niklasfrykholm** [comment]
Yes, this works for me in v0.13.1.
