### ISSUE TITLE
Can't open files with math

### ISSUE THREAD

**Issue by technic** [rhiokim/haroopad#471]
### bug

I have enabled MathJax in haroopad v0.13
I started editting, and math works ok except of issue #467. I saved my document and closed editor.
When I try to open .md file again with math inside I get the following error in _.config/Haroopad/.error/***.log_

```
 Information | Description 
-------------|-----------------------------
 Type        | UncaughtException 
 Date        | Mon Feb 16 2015 00:30:49 GMT+0200 (EET)
 Agent       | Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.104 Safari/537.36
 Stack       | ReferenceError: MathJax is not defined
    at processMathJax (file:///tmp/.org.chromium.Chromium.R7gZSq/js/viewer.min.js:62:3200)
    at drawMathJax (file:///tmp/.org.chromium.Chromium.R7gZSq/js/viewer.min.js:62:3456)
    at update (file:///tmp/.org.chromium.Chromium.R7gZSq/js/viewer.min.js:62:5568)

 Information | Description 
-------------|-----------------------------
 Type        | Error
 Date        | Mon Feb 16 2015 00:30:49 GMT+0200 (EET)
 Agent       | Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.104 Safari/537.36
 File        | file:///js/viewer.min.js
 Line Number | 62
 Message     | Uncaught ReferenceError: MathJax is not defined
```

Markdown file with math could contain any math code, for example, the bug occurs with the following file

```
test $$$x$$$ inline
```
### bonus :)

So after haroopad have failed to open file it was staying in background, and I decided to open file without math. I succeeded and then turned off MathJax in settings, all previous documents with math?that I tried to open before, appeared in front of me.

I am running **ArchLinux**

**Comment by nykh** [comment]
Thank you I just had this problem! What this can get worse is, when some file crashed with math in it, Haroopad can try to open it as "restored" on start, and so won't even start. I for once thought the program was corrupted and reinstalled it but of course that doesn't work without clearing .config/Haroopad/

As a temporary workaround I have to disable Math and disable Last File Restore.

**Comment by rhiokim** [comment]
@technic Thanks for the reporting.
It'll be fixed with next release version.
