### ISSUE TITLE
Name conflicts for header names are not completely resolved

### ISSUE THREAD

**Issue by da-z** [rhiokim/haroopad#475]
Some documents contain headers that have the same text value. The TOC works by transforming the header name into an HTML anchor hash. However the hash needs to be unique inside a document.

The TOC generation works as expected, by adding an suffix (-1, -2, -3, etc) for every duplicate header name. However, in the body of the document this process does not happen. The effect is that some links in the TOC do not work since they point to non-existing anchor hashes.

The following markdown can be used as a test case:

``` markdown
[TOC]

# List
## item
## item
## item
```

**Comment by rhiokim** [comment]
It'll be fixed with next release
