### ISSUE TITLE
Pressing number '6' results in inputting '###### 6' instead

### ISSUE THREAD

**Issue by hkjinlee** [rhiokim/haroopad#476]
Tested on Windows version 0.13.0. (Mac version looks good)

When keyboard 6 pressed, '###### 6' is shown instead. 
Please refer to the screenshot below.

![2015-02-25 10 13 10](https://cloud.githubusercontent.com/assets/7744953/6363052/ee57aeaa-bcd6-11e4-9fce-fb19e4b34939.png)

**Comment by rhiokim** [comment]
duplicated https://github.com/rhiokim/haroopad/issues/447
