### ISSUE TITLE
weired response when `ctrl+2` then number `6`

### ISSUE THREAD

**Issue by mcdoyaji** [rhiokim/haroopad#478]
when i input `ctrl+2` and then input number ends 6 .

(6... 16...)

`##` automaticaly increase `######`

i'm using haroopad v0.13.0

below is screenshot.

![number6response](https://cloud.githubusercontent.com/assets/11155414/6371543/2fee012a-bd40-11e4-9023-781a4239738b.png)

**Comment by rhiokim** [comment]
duplicated #447
