### ISSUE TITLE
Restoring files -- disable feature

### ISSUE THREAD

**Issue by prashrock** [rhiokim/haroopad#479]
Hi Kim,
Can you please provide an option to disable file restoring. Haroopad takes a long time to start across 3 platforms (Mac, Ubuntu 14.04, Windows 7) just because its trying to restore a bunch of old files. It would be great if you could give me an option to start Haroopad without restoring any previous files...
Thanks,
-Prashanth.

**Comment by rhiokim** [comment]
@prashrock Do you want this?
`Preferences > General > checkbox Enable Last File Restore`

**Comment by prashrock** [comment]
Sure, sounds good. Thanks !
