### ISSUE TITLE
align check boxes in task lists with bullet points of regular lists

### ISSUE THREAD

**Issue by Cathryne** [rhiokim/haroopad#480]
The indentation of 2nd (and following) text rows is incoherent between regular and tasks lists, because check boxes don't align with bullet points.

![haroopad-task-list-indent](https://cloud.githubusercontent.com/assets/757323/6481603/42aebdd0-c25f-11e4-98ae-7215c6f7d3f4.png)

In GitHub's own Markdown, it's coherent:
- regular
- [ ] task 
- also for very looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong list items
- [ ] also for very looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong list items

**Comment by rhiokim** [comment]
Thanks idea. :-)
It'll be improved in the next version

**Comment by Cathryne** [comment]
Neat solution, thank you :-)

**Comment by rhiokim** [comment]
@Cathryne :-)

**Comment by rhiokim** [comment]
it'll be fixed with next release
