### ISSUE TITLE
Mermaid rendering is not complete

### ISSUE THREAD

**Issue by sebelk** [rhiokim/haroopad#483]
Hi folks,
I've seen that some mermaid code is not rendered at all by haroopad, for example the following example:

``` mermaid
graph LR;
A == text ==> B;
```

It doesn't work, but with mermaid cli does it:

![Example mermaid link with text](https://cloud.githubusercontent.com/assets/4109256/6542692/54de068c-c4df-11e4-880d-a2a8594eb0ff.png)

Any ideas?

**Comment by rhiokim** [comment]
New version is out. v0.13.1 
Could please check this issue.

**Comment by da-z** [comment]
Hi. I installed `v0.13.1`. Just like `v0.13.0`, syntax highlight and mermaid rendering is not happening by default. Both are related to a sort of fenced code block processing I think.

I have found a workaround in which I have to go to File -> Preferences -> Markdown and click 'Apply'. Now syntax highlighting and mermaid rendering works in the preview pane, until I close the program.

**Comment by rhiokim** [comment]
It'll be fixed with v0.13.2
