### ISSUE TITLE
Can I use my external editor?

### ISSUE THREAD

**Issue by ssohjiro** [rhiokim/haroopad#488]
I usually use the VIM editor.
The file opened by haroopad does not reflect by other external editor like a VIM Editor.
Plus, haroopad does not any alert that this file was modified.
( It may lost the modified contents from other editor )

I suggest the feature that always watch the file's modification and when file is updated, immediately refresh the file. I think this feature may replace 'vim key binding' in haroopad.

Thank you.

---

평소에 빔 에디터를 사용하는데요,
하루패드로 작업하던 파일을 동시에 빔(또는 다른 편집기)으로 열어 편집할때 자동으로 수정내용이 갱신되지 않습니다. 또 다른 곳에서 수정된 파일을 하루패드에서 편집하고 저장하려할때 파일 내용이 변경되었다고 아무런 메시지가 뜨지 않습니다. (다른 곳에서 편집한 내용을 잃어버릴 위험이 있습니다)

예전에 저도 개인적으로 markdown을 web에서 사용하기위해 nodejs 와 web socket을 사용해서 간단하게 만들어 사용한 적이 있었는데요, (haroopad 를 보자마자 접어버렸지만요^^) nodejs 의 file watcher? 라이브러리를 사용하여 파일의 변경을 감지했었는데 하루패드에도 이런 기능이 추가되었으면 참 좋겠습니다! ^^
(이런 기능이 생기면 vim key binding 기능을 대체 해도 될것 같습니다)

좋은 앱 만들어 주셔서 감사합니다.
유용하게 사용하고 있습니다!

**Comment by rhiokim** [comment]
리포팅 감사드립니다. :-)
해당 기능은 지원했던 기능인데 최근 큰 변경으로 기능이 제대로 동작하지 않네요.
다음 버젼에 반영될 수 있도록 하겠습니다.

**Comment by rhiokim** [comment]
v0.13.2 릴리즈에 수정될 예정됩니다.
