### ISSUE TITLE
Mermaid rendering broken

### ISSUE THREAD

**Issue by hannesgredler** [rhiokim/haroopad#490]
Hi,

when i open below markdown file which contains two mermaid graphs, haroopad v 0.13.1 (Mac OSX) renders it just fine. As soon as i start editing the second mermaid graph (changing one line title) then the second
graph is not rendered at all
# Overview
# Table of contents

[TOC]
## Graph 1

``` mermaid
graph LR;

Input-->|import|App;
App-->|export|Output;
App-->FIB;

style Input fill:#88f;
style Output fill:#88f;
style App fill:#f88;
style FIB fill:#ff8;
```
## Graph 2

``` mermaid
graph TD;
Input-->|hash 1/4|App1;
Input-->|hash 2/4|App2;
Input-->|hash 3/4|App3;
Input-->|hash 4/4|App4;

style Input fill:#88f;
style App1 fill:#f88;
style App2 fill:#f88;
style App3 fill:#f88;
style App4 fill:#f88;
```

**Comment by MikhailBo** [comment]
Hi,

On Windows 8.1 behavior slightly different - when you edit 2nd graph than 1st graph start rendering metadata from 2nd graph and 2nd graph not rendering at all (white block). Editing metadata for 1st graph not affect on 2nd graph rendering.

**Comment by eidng8** [comment]
@MikhailBo 
A bit further, if I removed the first chart, say Ctrl+X to cut it, and then add it back (Ctrl+V), the both charts come out correctly again.

The whole edit/cut/paste process goes round and round as I keep editing :persevere:

**Comment by sebelk** [comment]
+1 Same problem on Fedora 22.

Also it "works" the following, Ctrl+a, Del, and Ctrl+z

**Comment by fterrier** [comment]
+1 here

**Comment by rhiokim** [comment]
It'll be fixed with next release.

**Comment by mingoal** [comment]
This is great app.
One question is when the release include this fix will be published?

**Comment by Jerome2606** [comment]
+1 to include this fix as it is not fixed today

**Comment by lehelmatyus** [comment]
+1 
had to do the  Ctrl+X to cut it, and then add it back (Ctrl+V) trick @eidng8 suggested.
