### ISSUE TITLE
Gantt Graph are blacken

### ISSUE THREAD

**Issue by cyrusn** [rhiokim/haroopad#499]
Hi, 

All bar are black in gantt graph, you may need to set the following option

``` js
mermaid.ganttConfig{
    numberSectionStyles: 4
}
```

please ref: [mermaid gantt config](http://knsv.github.io/mermaid/gantt.html#configuration)

e.g. The bars in Gantt Graph are all black.

<pre>
<code class="markdown">
``` mermaid
gantt
    title A Gantt Diagram
    section Section
    A task           :a1, 2014-01-01, 30d
    Another task     :after a1  , 20d
    section Another
    Task in sec      :2014-01-12  , 12d
    anther task      : 24d
```
</code>
</pre>

**Comment by rhiokim** [comment]
Thanks for the reporting :-)
It'll be fixed with next release (v0.13.2)
