### ISSUE TITLE
MathJax Inline problem

### ISSUE THREAD

**Issue by cyrusn** [rhiokim/haroopad#501]
Hi, 

If there are `text` before the inline equation, it fails to parse as inline but paragraph

e.g. all equations will be parsed as paragraph

``` markdown
# MathJax
My math is so rusty that I barely remember the _quadratic equation_:

When $$$a \ne 0$$$, there are two solutions to $ax^2 + bx + c = 0$ and they are
$$x = {-b \pm \sqrt{b^2-4ac} \over 2a}$$
```

In the following example,  equations can be parse as inline. as no word before the inline equation.

``` markdown
# MathJax 
My math is so rusty that I barely remember the _quadratic equation_:

$$$a \ne 0$$$, there are two solutions to $ax^2 + bx + c = 0$ and they are
$$x = {-b \pm \sqrt{b^2-4ac} \over 2a}$$
```

**Comment by diegoaguilar** [comment]
Any advance on this? I'm using `v0.13.1` on Ubuntu 14.04 and got same issue, too.

**Comment by digizeph** [comment]
Confirmed on Mac El Capitan.

**Comment by lucainnocenti** [comment]
Confirmed on Windows 10 with v0.13.1

**Comment by rhiokim** [comment]
It'll be fixed with v0.13.2

**Comment by aphirst** [comment]
Really excited to see this feature working!

**Comment by riturajkaushik** [comment]
Still waiting for this fix..

**Comment by st3inum** [comment]
Still waiting for this fix....
