### ISSUE TITLE
files with special characters or spaces are opened with garbled filename

### ISSUE THREAD

**Issue by XelaRellum** [rhiokim/haroopad#507]
Filenames that contain special characters or spaces are opened with short/garbled filename. This happens on Windows (specifically Windows 7)

In the registry the type "haroopad" has the shell command:
(path too haroopad)\haroopad.exe %1

When i change this too 
(path too haroopad)\haroopad.exe "%1"
it works as expected.

Please consider open sourcing the installer as well.

**Comment by rhiokim** [comment]
@XelaRellum Great thanks for the reporting.
It'll be fixed with next release.

**Comment by rhiokim** [comment]
link #527
