### ISSUE TITLE
Two diagram in one file 

### ISSUE THREAD

**Issue by ascrutae** [rhiokim/haroopad#510]
I draw two diagrams in one file, but editor only show the lastest diagram, here is the pictures.

![qq 20150516112746](https://cloud.githubusercontent.com/assets/12436447/7664522/978434c8-fbbe-11e4-8b44-e48d41c15e10.png)

**Comment by rhiokim** [comment]
link #490

**Comment by shadowbq** [comment]
:+1:

**Comment by rhiokim** [comment]
It'll be fixed with next release.

**Comment by ascrutae** [comment]
Good, Thanks

**Comment by sebelk** [comment]
+1
