### ISSUE TITLE
Haroopad Footer

### ISSUE THREAD

**Issue by iamunknown2** [rhiokim/haroopad#519]
I am aware that ~~Haroopad is open source~~ wait - is it? However, whenever you export/print the Markdown, there's a watermark (footer tag) (that is easily removable):

![glitch](https://cloud.githubusercontent.com/assets/11188939/8227324/f2826ac8-15d8-11e5-92cd-aa00b6e74f31.png)

I think we should ~~provide an option (no freemium) to print/export the footer/HTML as well~~ remove the feature entirely, to make it easier for the newbies who want to make a site without much knowledge of HTML.

**Comment by rhiokim** [comment]
It's not big issue for Haroopad. I would remove it in the next version. :-)
