### ISSUE TITLE
Syntax highlighting of HTML doesn't work

### ISSUE THREAD

**Issue by ghost** [rhiokim/haroopad#520]
My haroopad is v0.13.1 and platform is windows7_x64.
![haroopad_html_highlight](https://cloud.githubusercontent.com/assets/7036875/8304987/580d2e48-19dd-11e5-9769-0e2698fe0440.png)
Is it a bug or an unsupported feature?

**Comment by juaalta** [comment]
If you look at the following link http://pad.haroopress.com/page.html?f=how-to-write-fenced-code-block to display the syntax highlighting of HTML you need to use the `xml` tag and not the `html` tag.

**Comment by rhiokim** [comment]
@juaalta Thanks response. And It seems not so bad support `html` keyword for syntax highlighting in the next version.

**Comment by ghost** [comment]
◑﹏◐I should learn markdown again
@juaalta thanks for your help
@rhiokim thanks for your excellent work

**Comment by rhiokim** [comment]
It'll be fixed with next release.
