### ISSUE TITLE
TOC does not show headline level 1

### ISSUE THREAD

**Issue by shelper** [rhiokim/haroopad#524]
when i put a simple file as 

```
[TOC]
# test
## test2 
```

the TOC only list level 2 headline, level one is missing...

**Comment by rhiokim** [comment]
@shelper 

I has a some history.
- http://haroopad.userecho.com/topic/359034-toc/
- http://haroopad.userecho.com/topic/455504-toc-does-not-show-headers/

and look at the wikipedia articles which can be seen.
