### ISSUE TITLE
Program failing to launch on Mac OS X

### ISSUE THREAD

**Issue by louim** [rhiokim/haroopad#525]
Running most recent version `0.13.1` downloaded from Bitbucket.

Seems like it's the same issue that #489, #437 and #450.

Here is what I see in `Library/Application\ Support/Haroopad/.error/2015/07/18.log`

```
Information | Description 
-------------|-----------------------------
 Type        | UncaughtException 
 Date        | Sat Jul 18 2015 21:49:53 GMT-0400 (EDT)
 Agent       | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.104 Safari/537.36
 Stack       | SyntaxError: Unexpected string
    at Object.parse (native)
    at file:///var/folders/hp/9r441d9d0m379960258kz7pw0000gn/T/.org.chromium.Chromium.3m5rcv/js/app.js:3:13032
    at Array.forEach (native)
    at load (file:///var/folders/hp/9r441d9d0m379960258kz7pw0000gn/T/.org.chromium.Chromium.3m5rcv/js/app.js:3:12938)
    at file:///var/folders/hp/9r441d9d0m379960258kz7pw0000gn/T/.org.chromium.Chromium.3m5rcv/js/app.js:3:13343
    at app (file:///var/folders/hp/9r441d9d0m379960258kz7pw0000gn/T/.org.chromium.Chromium.3m5rcv/js/app.js:3:13411)
    at file:///var/folders/hp/9r441d9d0m379960258kz7pw0000gn/T/.org.chromium.Chromium.3m5rcv/index.html:1:176

 Information | Description 
-------------|-----------------------------
 Type        | Error
 Date        | Sat Jul 18 2015 21:49:53 GMT-0400 (EDT)
 Agent       | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.104 Safari/537.36
 File        | file:///var/folders/hp/9r441d9d0m379960258kz7pw0000gn/T/.org.chromium.Chromium.3m5rcv/index.html
 Line Number | 50
 Message     | Uncaught SyntaxError: Unexpected string
```

**Comment by rhiokim** [comment]
Could you please tell me your system locale?
I found that it does not operate properly in a particular locale.

`Your Mac > System Preference > Language & Region > Preferred languages`

**Comment by louim** [comment]
I have "Français" as my primary language. Secondary is "English"

**Comment by ghost** [comment]
Same issue here. It works if you put "English" as primary language in OS X "preference". But "French" prevent the GUI to launch.

**Comment by ghostlevel** [comment]
Same here on Mac OSX. I could launch it after changing the language to English. I haven't checked but i couldn't launch this version on Windows and Linux either, if that's the same problem ("Français" / French as System Language for both).

**Comment by rhiokim** [comment]
I've made new pkg for next release. **it's release candidate version, not official**
- https://www.dropbox.com/sh/o0gsowztbuumoig/AABcDuphGXImM_i7Vb4hPVIla?dl=0

Hi there!
This package works fine for me (OS X El Capitan - Français)

**Comment by rhiokim** [comment]
It'll be fixed with next release
