### ISSUE TITLE
[suggest] some text invisiblility feature

### ISSUE THREAD

**Issue by soulawaker** [rhiokim/haroopad#529]
Hi, rhiokim

I suggest some text invisibility feature.

I use haroopad to translate documents, writing an original sentence first and appending translated one second.

I need the original text visible in editor and invisible in viewer, just like CSS 'display:none' style.

I'm not sure how many people need this feature, but it'll be very useful for comparing and correcting translated text.

Regards
soulawaker

**Comment by nykh** [comment]
How about

**Comment by soulawaker** [comment]
wow! thanks! it's worked.
