### ISSUE TITLE
Your software doesn't support Chinese very well

### ISSUE THREAD

**Issue by duoduoeeee** [rhiokim/haroopad#534]
When I edit a document with your HarooPad Chinese characters don't show up in the editor but they appear in the preview section.
I'm using your HarooPad in Windows7 x64.BTW in Ubuntu there is no such issue.

**Comment by rhiokim** [comment]
duplicated #505 
It'll be fixed with next release.
and you can get solution here  https://github.com/rhiokim/haroopad/issues/505#issuecomment-119784365
