### ISSUE TITLE
탐색기에서 파일을 더블클릭하여 열었을 때 8.3파일 이름으로 표시되는 문제

### ISSUE THREAD

**Issue by steamb23** [rhiokim/haroopad#540]
Fallen Dignity.md라는 파일이 있을때,
하루패드를 정상적으로 실행후 열기를 하면 긴 이름이 적용되어 제대로 표시됩니다.
![2015-10-07 01_47_35-](https://cloud.githubusercontent.com/assets/6805899/10315467/7440f85a-6c95-11e5-8467-32bf1990303b.png)
그러나 탐색기에서 파일을 클릭하여 실행할 경우 8.3이름이 적용되어 잘려나옵니다.
![2015-10-07 01_47_46-](https://cloud.githubusercontent.com/assets/6805899/10315468/7443f24e-6c95-11e5-927e-781d08e24a49.png)

심각한 문제점은 아니지만 굉장히 거슬리게 느껴집니다. 차기버전에서 수정되었으면 좋겠네요.

**Comment by steamb23** [comment]
#430 의 두번째 코멘트에서 해당 문제점이 제기됬지만 못보고 넘어가신 듯 하네요.

**Comment by wuxinxinggg** [comment]
will you use english to descript the question and others, it's really  pained for us to understand,please.
THX

**Comment by steamb23** [comment]
sorry, wuxinxingg.
I did not consider people I do not know Korean.
I'll translate for the posts.
Note that I do not speak English well.

If there is a file called Fallen Dignity.md,
After running the Haroopad Normally, when you open a file is subject to the Long Name is displayed correctly.
However, if you click on a file in Explorer to run, this name will appear cut off of 8.3 is applied.
I hope corrected in the next version.

**Comment by rhiokim** [comment]
It'll be fix with next release.(>=v0.13.2)
