### ISSUE TITLE
Can't open file if the name includes spaces

### ISSUE THREAD

**Issue by user4815162342** [rhiokim/haroopad#543]
Using Ubuntu 12.04, Haroopad 0.13.1. When I attempt to open a file from the command line whose name contains spaces, it opens up a blank, new file.

```
$ echo "test" > foo\ bar.md
$ haroopad foo\ bar.md
```

Expected the document to contain the word "test", but instead got a blank document, and when saved, prompted me for a file name defaulting to "Untitled.md". I got the same results by opening the file from a file manager. 

Meanwhile, doing the same thing with a filename that doesn't contain spaces works as expected.

**Comment by rhiokim** [comment]
It'll be fixed with next release.
