### ISSUE TITLE
순수 HTML 복사하였을 때, 코드 하이라이트

### ISSUE THREAD

**Issue by choiseungho** [rhiokim/haroopad#553]
코드 하이라이트 border 문제

코드 하이라이트 안에 border: 1px solid rgb(204, 204, 204); 이 부분이 추가되서 위지웍에디터에 복사하고 나면 코드에 border가 생성 됩니다. 이 것을 제거 해주실 수 있으신가요?

![1](https://cloud.githubusercontent.com/assets/7479257/11292107/836f8cb4-8f8c-11e5-9840-6dadde7995a8.png)

**Comment by rhiokim** [comment]
**Yes I can do this** :-)
It'll be fixed with next release.
