### ISSUE TITLE
Haroopad don't run

### ISSUE THREAD

**Issue by khawarizmus** [rhiokim/haroopad#557]
hello 
i have windows 7 64 bit and i installed Haroopad on my laptop but when lunching it nothing happen the software don't run 
i tried to change the properties to run as administrator or to change the compatibility to vista but still same thing the software doesn't run 
and i can see in the task manager that there is two process of haroopad working 
any solution ?

**Comment by poulpix** [comment]
Exactly the same here with W7 32 bits.

**Comment by Nikhil1618** [comment]
Hi,
I have exactly the same problem here on a windows 7 64 bits.

**Comment by fchevassu** [comment]
Hello,
I also have the exact same symptoms (on Windows 7 64 bits).
Uninstalling/resinstalling Haroopad did not change anything.

**Comment by Aloike** [comment]
Same here, W7 64bits...
