### ISSUE TITLE
using "width" with images doesn't work with shared links from dropbox

### ISSUE THREAD

**Issue by a2jww** [rhiokim/haroopad#558]
Hi there
I'm using shared links from Dropbox to show dedicated pictures in my markdown documents.

But when using the following form, attributes like "width" do not seem to work:

`![](https://www.dropbox.com/s/sqnkd919j2si9ft/testpicture.jpg?dl=1 'width:100px;float:right')`

I can see the picture (in maximum size), but width isn't reduced in this case.

any wrong settings? Or is the dropbox link the reason for that?

Andreas

**Comment by rhiokim** [comment]
Default image syntax is `![alt text](url "title")`
It's required.

Additionally Haroopad does support `style` option
So if you want to use style option, please write like this `![alt text](url "" "width:100px:float:right")`
