### ISSUE TITLE
이메일 보내기 안되요.

### ISSUE THREAD

**Issue by hjs1543** [rhiokim/haroopad#560]
이메일을 gmail로 설정하고 하는데... 계속 sending만 하고 있음. 어디서 걸려있는지 비밀번호가 틀린 건지... 좀 자세한 내용을 보여주게 할 수 없나요. 이유가 뭘까요?  sending만 계속 반복...

**Comment by rhiokim** [comment]
메일 전송 오류가 발생하는 현재까지 파악된 경우는 2가지입니다.
1. 하루패드 실행 이후 한번이라도 비밀번호 입력 오류가 있을 경우 **하루패드를 재 실행**해야 합니다.
   - 새로운 창을 열어서 시도해도 동일하게 메일 전송이 되지 않습니다.
2. 구글 로그인 방식을 2단계 인증을 사용하는 경우 기술적인 졔약으로 메일 기능을 이용할 수 없습니다.
   - https://myaccount.google.com/security?pli=1#signin
