### ISSUE TITLE
Font Awesome

### ISSUE THREAD

**Issue by sebelk** [rhiokim/haroopad#563]
Hi,

Does Haroopad support Font Awesome?

(http://fortawesome.github.io/Font-Awesome/icons/)

Thanks in advance!

**Comment by rhiokim** [comment]
Font Awesome does not built in Haroopad.
But you can use this. follow step.
1. Open the preference dialog <kbd>CMD</kbd>+<kbd>,</kbd>
2. Click the `Viewer` tab
3. Click the blue `Edit` button
4. Open `default.css` file
5. Insert this syntax into the file  `@import url("https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css");`
6. Save and close
7. Click the `Reload` button
8. Done
9. Write the `<i class="fa fa-bluetooth"></i>` into editor area

**Comment by rhiokim** [comment]
Is it work for you?

**Comment by salvob41** [comment]
Thank you! 
Does this work for mermaid  too?  As explained here: https://mermaidjs.github.io/flowchart.html 
example: 
```mermaid
graph TD
    B["fa:fa-twitter for peace"]
    B-->C[fa:fa-ban forbidden]
    B-->D(fa:fa-spinner);
    B-->E(A fa:fa-camera-retro perhaps?);
```
