### ISSUE TITLE
[pt_BR] Locales: Found typo on menu

### ISSUE THREAD

**Issue by devdrops** [rhiokim/haroopad#567]
On locales: the item `insert.underline` have a typo on the translation. The correct translation for `underline` is `Sublinhado`.

<img width="309" alt="captura de tela 2016-02-18 as 11 35 33" src="https://cloud.githubusercontent.com/assets/1259313/13144801/daa8d4e8-d633-11e5-88b6-d650df42c20a.png">

I'll submit a pull request for this small fix.

**Comment by rhiokim** [comment]
I'll be applied with v0.13.2

**Comment by devdrops** [comment]
Great! :+1:
