### ISSUE TITLE
two mermiad code snippets only 1 will display

### ISSUE THREAD

**Issue by oliveagle** [rhiokim/haroopad#585]
![image](https://cloud.githubusercontent.com/assets/2270205/17391336/c8c1f1d6-5a47-11e6-9c9f-71c1b219b6ee.png)

**Comment by rhiokim** [comment]
It was fixed with v0.13.2-rc version (It's not released officially yet)
You can download it here - https://bitbucket.org/rhiokim/haroopad-download/downloads
