### ISSUE TITLE
when Ctrl+V Input cursor changed insert mode

### ISSUE THREAD

**Issue by ghost** [rhiokim/haroopad#83]
OS : Ubuntu 13.04

when i put 'ctrl+v' in haroopad, input cursor changed into insert mod. 

and can't delete nothing .. 

solution is type 's' key on you keyboard.

then, the cursor back to original input mode. and all good.

I think it's bug,

**Comment by rhiokim** [comment]
Vim keybinding toggling shortcut change from `ctrl + shift + v` to follow 
- MAC OS : COMMAND + Option(alt) + V
- Window or Linux : Ctrl + Alt + V

I'll adjust next build vesion (v0.4.3,  now v0.4.1).

**Comment by ghost** [comment]
잘 되서 너무 좋습니다. 굿럭요!!! ^^
