### ISSUE TITLE
window 버전 설치 시 알약에서 악성코드로 보고 치료..

### ISSUE THREAD

**Issue by r2fresh** [rhiokim/haroopad#93]
![haoopad_](https://f.cloud.github.com/assets/329343/751573/f79e5aec-e503-11e2-9893-30f8c5fd7f32.png)

윈도우 버전을 설치하는데 알약에서 악성코드가 설치되어 있다고, 치료 하겠냐 해서 치료하니 치료는 됨
혹시 다른데에서도 악성코드라는 말이 뜰 수 있다고 생각함

그리고 크롬에서 다운로드하는 하는 나쁜파일이라고도 하네 그건 계속 버튼을 누르고 해서 진행하면 되긴 하지만 ^^

윈도우 버전을 설치한 다른 분들에게도 물어보는게 좋을듯 ^^

**Comment by rhiokim** [comment]
Oh~ thanks!

치료되고 실행하는데는 아무런 지장 없나요?

**Comment by r2fresh** [comment]
64bit에 32bit용을 설치해서 그런가? 

2가지 경우를 테스트 해봤지
1. 설치 후 알약에서 치료 하라고 했지만 치료하지 않고 haroopad.exe파일을 실행
   => 실행 안되고 "지정한 장치, 경로 또는 파일을 액세스할 수 없습니다. 이 항목을 엑세스하는 데 필요한 권한을 가지고 있지 않습니다" 라고 경고창이 뜨고 실행이 안됨
2. 알약으로 악성코드를 치료하면 haroopad.exe파일이 삭제됨

**Comment by rhiokim** [comment]
I coped. thanks R2
